
#--------------------------------------------------------
#LISTA PARA HACER Y MEJORAR EL SISTEMA DEL TPE
#--------------------------------------------------------
# 25-03-26 'ADD AUMENTAR EL TIPO DE RESOLUCION AUMENTAR "ART. 118" y ADMINISTRATIVO (CASO DE ASCENSO, CONSIDERACION DE FRONTERA)'
# ADD EN EL TIPO DE AUTO "REHABILITACION DE DERECHOS PROFESIONALES"

    ADD NUMERO CORRELATIVO DEL NUMERO DE RESOLUCION EN AUTOMATICO

BD FIX SACAR ID_ABOG DE LA TABLA SIM    (PORQUE CADA ABOGADO NO REALIZA CADA SIM SINO RES Y AUTO)
   
  
BD FIX EN LA TABLA AUTOTPE NO TODOS LOS AUTOS SON ANEXADOS AL SIM DE REPENTE SERIA AUMENTAR EN SIM UN SELECT 
        DE INGRESO DE UN SIM U OTRO Y AL LADO COLOCAR LA MOTIVACION PARA QUE SEA TRATADO EN EL TPE. 
        EJ. AMADO OSWALDO QUISPE MAMANI SU AUTO (AUTO DE VISTA 42/18 DE FECHA 19-NOV-18)
    
EN LA TABLA RES HAY QUE HABILITAR UNA SELECT PARA SIM Y OTRO ADMINISTRATIVO (POSESION TPE, ASCENSO DE GRALES)ETC.