"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
import os
import pymysql
pymysql.version_info = (2, 2, 1, "final", 0)
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])

# Origenes de confianza para CSRF (necesario detras de proxy/HTTPS).
# Configurar en .env como: CSRF_TRUSTED_ORIGINS=https://tpe.ejercito.bo,https://otrohost
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',  # django-axes: rate limiting de login
    'simple_history',  # django-simple-history: auditoría de cambios
    'tpe_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # django-axes: detectar intentos fallidos
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tpe_app.middleware.SessionDiagnosticsMiddleware',  # Diagnóstico de sesión
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'tpe_app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='3306'),
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},  # Endurecido para sistema judicial
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Mayuscula + minuscula + digito + simbolo
        'NAME': 'tpe_app.utils.password_validators.ComplejidadPasswordValidator',
    },
]


# Session & CSRF Cookies
# Por defecto se exige HTTPS en producción (DEBUG=False) y se permite HTTP en
# desarrollo (DEBUG=True). En LAN sin HTTPS poner USE_SECURE_COOKIES=False en .env.
USE_SECURE_COOKIES = env.bool('USE_SECURE_COOKIES', default=not DEBUG)

SESSION_COOKIE_AGE = 30 * 60
SESSION_SAVE_EVERY_REQUEST = True   # renueva el timeout en cada request (inactividad, no tiempo absoluto)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = USE_SECURE_COOKIES
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'

CSRF_COOKIE_SECURE = USE_SECURE_COOKIES
CSRF_COOKIE_HTTPONLY = True   # JS no necesita leer el token; Django lo inyecta en forms
CSRF_COOKIE_SAMESITE = 'Strict'

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HSTS solo en HTTPS real. Para un sistema judicial los defaults son seguros:
# - SECURE_SSL_REDIRECT=True fuerza HTTPS en todas las requests.
# - SECURE_HSTS_SECONDS=1 ano (31536000) instruye al navegador a usar siempre HTTPS.
# Si necesita desactivarlos temporalmente (ej. primera puesta en marcha), poner
# SECURE_SSL_REDIRECT=False y SECURE_HSTS_SECONDS=0 en .env.
if USE_SECURE_COOKIES and not DEBUG:
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False

# Upload limits (5 MB para evitar DoS por upload masivo)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-bo'

TIME_ZONE = 'America/La_Paz'  # Bolivia UTC-4

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# ✅ CONFIGURACIÓN CORRECTA PARA ARCHIVOS ESTÁTICOS
# Django busca automáticamente en: tpe_app/static/

# STATIC_ROOT es donde Django copia los archivos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if not DEBUG
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

# Media files (fotos PM, PDFs adjuntos)
# La ruta OneDrive es igual en ambas PCs, solo cambia el nombre de usuario.
# Path.home() resuelve a C:/Users/Dell en laptop y C:/Users/user en trabajo.
MEDIA_URL = '/media/'
MEDIA_ROOT = env(
    'MEDIA_ROOT',
    default=str(Path.home() / 'OneDrive' / '1. TPE' / '2. TPE GRAL' / 'media_tpe')
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # django-axes (debe ir primero)
    'django.contrib.auth.backends.ModelBackend',  # Django default
]

# django-axes: Protección contra fuerza bruta en login
from datetime import timedelta
AXES_FAILURE_LIMIT = 5  # Bloquear después de 5 intentos fallidos
AXES_COOLOFF_TIME = timedelta(hours=1)  # Cooloff de 1 hora
AXES_LOCKOUT_URL = '/login/'  # Redirigir a login si está bloqueado
AXES_LOCKOUT_TEMPLATE = 'axes/lockout.html'  # Template personalizado en tpe_app/templates/axes/
AXES_VERBOSE = True  # Loguear intentos
AXES_RESET_ON_SUCCESS = True  # Reset contador al login exitoso
AXES_LOCK_OUT_AT_FAILURE = True  # Bloquear al alcanzar el límite

# 🔑 IMPORTANTE: Bloquear por USUARIO, no por IP
# En producción es crítico para redes corporativas donde múltiples usuarios comparten la misma IP
# AXES_USE_USER_AGENT = False (no usar user-agent)
# Por defecto axes usa: username (si existe), luego IP. Lo forzamos a username cuando el usuario existe.
AXES_META_KEYS = ('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR')  # Intentar obtener IP real (proxy/NAT)
# En production con proxy: usar X_FORWARDED_FOR. Sin proxy: usar REMOTE_ADDR.

# Estrategia de bloqueo:
# - Si el usuario existe en la forma de login: bloquear el USERNAME (no la IP)
# - Si no existe: bloquear la IP (para prevenir enumeración de usuarios)
AXES_LEGACY_USER_LOCKOUT = False  # Desactiva bloqueo por IP cuando existe username válido

# ============================================================
# LOGGING
# ============================================================
# Tres canales:
#   - console: humano-legible, util en dev y para journalctl en prod
#   - file_app: logs de aplicacion rotados (10 MB x 10 archivos = 100 MB max)
#   - file_security: logs de seguridad rotados (10 MB x 30 archivos = 300 MB max).
#     Logger 'tpe_app.security' debe usarse para: cambios de rol, creacion de
#     usuarios, fallos repetidos de permisos, exports masivos, etc.
# La carpeta de logs se crea automaticamente si no existe.

LOG_DIR = Path(env('LOG_DIR', default=str(BASE_DIR / 'logs')))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} pid={process:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_app': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'tpe.log'),
            'maxBytes': 10 * 1024 * 1024,   # 10 MB
            'backupCount': 10,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
        'file_security': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'security.log'),
            'maxBytes': 10 * 1024 * 1024,   # 10 MB
            'backupCount': 30,              # ~300 MB de retencion
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'tpe_app': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'tpe_app.security': {
            'handlers': ['console', 'file_security'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file_app'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file_security'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['console', 'file_security'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
