# Generated by Django 6.0.2 on 2026-04-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rap',
            name='RAP_OFI',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='N° Oficio Elevación'),
        ),
    ]
