# Generated by Django 5.2 on 2026-04-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abog',
            name='ci',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='abog',
            name='especialidad',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='abog',
            name='materno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='abog',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='abog',
            name='paterno',
            field=models.CharField(max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número de Auto'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='especialidad',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='materno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='paterno',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='recursotsp',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número Resolución TSP'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='numero',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Número de Resolución'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='resolucion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_reconsideracion', to='tpe_app.resolucion', verbose_name='Resolución impugnada (solo RECONSIDERACION)'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='estado',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('PROCESO_EN_EL_TSP', 'Proceso en el TSP'), ('PROCESO_CONCLUIDO_TPE', 'Proceso Concluido (TPE)'), ('PROCESO_EJECUTADO', 'Proceso Ejecutado'), ('OBSERVADO', 'Observado')], db_index=True, default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='fase',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'En Espera de RAP (plazo 3 días)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('EN_AGENDA_EJECUTORIA', 'En Agenda (Auto de Ejecutoria)'), ('EN_EJECUTORIA', 'Auto de Ejecutoria Emitido'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorandum Retornado (Proceso Ejecutado)')], db_index=True, default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='fecha_ingreso',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Ingreso al TPE'),
        ),
        migrations.AlterUniqueTogether(
            name='resolucion',
            unique_together={('numero', 'instancia')},
        ),
    ]
