# Generated by Django 5.2 on 2026-04-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0002_delete_abog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursotsp',
            name='numero_oficio',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='N° Oficio Elevación'),
        ),
    ]
