# Generated by Django 6.0.3 on 2026-03-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0002_alter_pm_pm_escalafon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='PM_ARMA',
            field=models.CharField(blank=True, choices=[('INFANTERIA', 'Infantería'), ('CABALLERIA', 'Caballería'), ('ARTILLERIA', 'Artillería'), ('INGENIERIA', 'Ingeniería'), ('COMUNICACIONES', 'Comunicaciones'), ('INTENDENCIA', 'Intendencia'), ('SANIDAD', 'Sanidad'), ('JAM', 'JAM'), ('AVIACION', 'Aviación del Ejército'), ('POLICIA_MILITAR', 'Policía Militar')], max_length=20, null=True, verbose_name='Arma'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_ESTADO',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('FALLECIDO', 'Fallecido'), ('RESERVA_ACTIVA', 'Reserva Activa')], default='ACTIVO', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_GRADO',
            field=models.CharField(blank=True, choices=[('GENERAL_EJERCITO', 'General de Ejército'), ('GENERAL_DIVISION', 'General de División'), ('GENERAL_BRIGADA', 'General de Brigada'), ('CORONEL', 'Coronel'), ('TCNEL', 'Teniente Coronel'), ('MAYOR', 'Mayor'), ('CAPITAN', 'Capitán'), ('TENIENTE', 'Teniente'), ('SUBTENIENTE', 'Subteniente'), ('SUBOFICIAL_MAYOR', 'Suboficial Mayor'), ('SUBOFICIAL_MAESTRE', 'Suboficial Maestre'), ('SUBOFICIAL_1RO', 'Suboficial Primero'), ('SUBOFICIAL_2DO', 'Suboficial Segundo'), ('SUBOFICIAL_INICIAL', 'Suboficial Inicial'), ('SARGENTO_1RO', 'Sargento Primero'), ('SARGENTO_2DO', 'Sargento Segundo'), ('SARGENTO_INICIAL', 'Sargento Inicial'), ('CABO', 'Cabo'), ('SOLDADO', 'Soldado'), ('PROF_V', 'Prof. V'), ('PROF_IV', 'Prof. IV'), ('PROF_III', 'Prof. III'), ('PROF_II', 'Prof. II'), ('PROF_I', 'Prof. I'), ('TEC_V', 'Tec. V'), ('TEC_IV', 'Tec. IV'), ('TEC_III', 'Tec. III'), ('TEC_II', 'Tec. II'), ('TEC_I', 'Tec. I'), ('ADM_V', 'Adm. V'), ('ADM_IV', 'Adm. IV'), ('ADM_III', 'Adm. III'), ('ADM_II', 'Adm. II'), ('ADM_I', 'Adm. I'), ('APAD_V', 'Apad. V'), ('APAD_IV', 'Apad. IV'), ('APAD_III', 'Apad. III'), ('APAD_II', 'Apad. II'), ('APAD_I', 'Apad. I')], max_length=20, null=True, verbose_name='Grado'),
        ),
    ]
