# Generated by Django 6.0.3 on 2026-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0002_alter_rap_ofi_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='PM_ARMA',
            field=models.CharField(blank=True, choices=[('INF.', 'INF.'), ('CAB.', 'CAB.'), ('ART.', 'ART.'), ('ING.', 'ING.'), ('COM.', 'COM.'), ('INT.', 'INT.'), ('SAN.', 'SAN.'), ('TGRAFO.', 'TGRAFO.'), ('AV.', 'AV.'), ('MÚS.', 'MÚS.')], max_length=20, null=True, verbose_name='Arma'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_ESCALAFON',
            field=models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('OFICIAL SUPERIOR', 'OFICIAL SUPERIOR'), ('OFICIAL SUBALTERNO', 'OFICIAL SUBALTERNO'), ('SUBOFICIAL', 'SUBOFICIAL'), ('SARGENTO', 'SARGENTO'), ('TROPA', 'TROPA'), ('EMPLEADO CIVIL', 'EMPLEADO CIVIL')], max_length=20, null=True, verbose_name='Escalafón'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_ESTADO',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('RETIRO OBLIGATORIO', 'RETIRO OBLIGATORIO'), ('RESERVA ACTIVA', 'RESERVA ACTIVA'), ('BAJA', 'BAJA'), ('FALLECIDO', 'FALLECIDO'), ('NO HABIDO', 'NO HABIDO'), ('OTRO', 'OTRO')], default='ACTIVO', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_GRADO',
            field=models.CharField(blank=True, choices=[('GRAL. EJTO.', 'GRAL. EJTO.'), ('GRAL. DIV.', 'GRAL. DIV.'), ('GRAL. BRIG.', 'GRAL. BRIG.'), ('CNL.', 'CNL.'), ('TCNL.', 'TCNL.'), ('MY.', 'MY.'), ('CAP.', 'CAP.'), ('TTE.', 'TTE.'), ('SBTTE.', 'SBTTE.'), ('SOF. MTRE.', 'SOF. MTRE.'), ('SOF. MY.', 'SOF. MY.'), ('SOF. 1RO.', 'SOF. 1RO.'), ('SOF. 2DO.', 'SOF. 2DO.'), ('SOF. INCL.', 'SOF. INCL.'), ('SGTO. 1RO.', 'SGTO. 1RO.'), ('SGTO. 2DO.', 'SGTO. 2DO.'), ('SGTO. INCL.', 'SGTO. INCL.'), ('CABO', 'CABO'), ('DGTE.', 'DGTE.'), ('SLDO.', 'SLDO.'), ('PROF. V', 'PROF. V'), ('PROF. IV', 'PROF. IV'), ('PROF. III', 'PROF. III'), ('PROF. II', 'PROF. II'), ('PROF. I', 'PROF. I'), ('TEC. V', 'TEC. V'), ('TEC. IV', 'TEC. IV'), ('TEC. III', 'TEC. III'), ('TEC. II', 'TEC. II'), ('TEC. I', 'TEC. I'), ('ADM. V', 'ADM. V'), ('ADM. IV', 'ADM. IV'), ('ADM. III', 'ADM. III'), ('ADM. II', 'ADM. II'), ('ADM. I', 'ADM. I'), ('APAD. V', 'APAD. V'), ('APAD. IV', 'APAD. IV'), ('APAD. III', 'APAD. III'), ('APAD. II', 'APAD. II'), ('APAD. I', 'APAD. I')], max_length=20, null=True, verbose_name='Grado'),
        ),
    ]
