# Generated by Django 5.2.12 on 2026-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0003_alter_pm_pm_arma_alter_pm_pm_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raee',
            options={'ordering': ['-RAE_FEC'], 'verbose_name': 'RAEE — Aclaración, Explicación y Enmienda', 'verbose_name_plural': 'RAEE — Aclaración, Explicación y Enmienda'},
        ),
        migrations.RemoveField(
            model_name='sim',
            name='SIM_FECTPE',
        ),
        migrations.AddField(
            model_name='rap',
            name='RAP_FECLIMITE',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite remisión TSP (3 días hábiles)'),
        ),
        migrations.AddField(
            model_name='res',
            name='RES_EDICTO_FEC',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Edicto'),
        ),
        migrations.AddField(
            model_name='res',
            name='RES_EDICTO_PERIOD',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Periódico del Edicto'),
        ),
        migrations.AddField(
            model_name='rr',
            name='RR_FECLIMITE',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite (15 días hábiles)'),
        ),
        migrations.AddField(
            model_name='sim',
            name='SIM_ESTADO',
            field=models.CharField(choices=[('RADICADO_TPE', 'Radicado en el TPE'), ('PARA_AGENDA', 'Para Agenda'), ('EN_APELACION_TSP', 'En Apelación TSP')], default='RADICADO_TPE', max_length=20, verbose_name='Estado del Sumario'),
        ),
        migrations.AddField(
            model_name='sim',
            name='SIM_FECING',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso al TPE'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_FECNOT',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Notificación'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_HORNOT',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Notificación'),
        ),
        migrations.AlterField(
            model_name='rap',
            name='RAP_OFI',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N° Oficio Elevación'),
        ),
        migrations.AlterField(
            model_name='res',
            name='RES_TIPO',
            field=models.CharField(choices=[('SANCIONES_DISCIPLINARIAS', 'Sanciones Disciplinarias'), ('SANCION_ARRESTO', 'Sanción Arresto (Ejecutiva)'), ('SANCION_LETRA_B', 'Sanción Letra B (Pérdida de Antigüedad)'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('SANCION_BAJA', 'Sanción Baja'), ('SOLICITUD_LETRA_D', 'Solicitud Letra D (Permiso Médico)'), ('SOLICITUD_LICENCIA_MAXIMA', 'Solicitud Licencia Máxima'), ('SOLICITUD_ASCENSO', 'Solicitud de Ascenso'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'Solicitud de Restitución de Antigüedad'), ('ARCHIVO_OBRADOS', 'Archivo de Obrados'), ('OTRO', 'Otro')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_AUTOFINAL',
            field=models.TextField(blank=True, null=True, verbose_name='Auto Final / Dictamen'),
        ),
        migrations.AlterModelTable(
            name='abog',
            table='abog',
        ),
        migrations.AlterModelTable(
            name='autotpe',
            table='autotpe',
        ),
        migrations.AlterModelTable(
            name='autotsp',
            table='autotsp',
        ),
        migrations.AlterModelTable(
            name='pm',
            table='pm',
        ),
        migrations.AlterModelTable(
            name='pm_sim',
            table='pm_sim',
        ),
        migrations.AlterModelTable(
            name='raee',
            table='raee',
        ),
        migrations.AlterModelTable(
            name='rap',
            table='rap',
        ),
        migrations.AlterModelTable(
            name='res',
            table='res',
        ),
        migrations.AlterModelTable(
            name='rr',
            table='rr',
        ),
        migrations.AlterModelTable(
            name='sim',
            table='sim',
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOC_TABLA', models.CharField(choices=[('sim', 'Sumario SIM'), ('res', 'Resolución TPE'), ('rr', 'Segunda Resolución RR'), ('rap', 'Recurso de Apelación RAP'), ('raee', 'RAEE'), ('autotpe', 'Auto TPE'), ('autotsp', 'Auto TSP')], max_length=30, verbose_name='Tabla de origen')),
                ('DOC_ID_REG', models.BigIntegerField(verbose_name='ID del registro')),
                ('DOC_TIPO', models.CharField(choices=[('resolucion', 'Resolución'), ('auto', 'Auto'), ('recurso', 'Recurso'), ('sim', 'Sumario SIM'), ('notificacion', 'Notificación'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de documento')),
                ('DOC_RUTA', models.FileField(upload_to='documentos/%Y/', verbose_name='Archivo PDF')),
                ('DOC_NOMBRE', models.CharField(max_length=100, verbose_name='Nombre descriptivo')),
                ('DOC_FECREG', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
                'db_table': 'documentos_adjuntos',
                'indexes': [models.Index(fields=['DOC_TABLA', 'DOC_ID_REG'], name='DOC_TABLA_ID')],
            },
        ),
    ]
