# Generated by Django 5.2 on 2026-04-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0003_feriadobolivia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotpe',
            name='fecha_notif',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='hora_notif',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='memo_fecha',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='memo_fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='memo_numero',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='notif_a',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='tipo_notif',
        ),
        migrations.RemoveField(
            model_name='autotsp',
            name='fecha_notif',
        ),
        migrations.RemoveField(
            model_name='autotsp',
            name='hora_notif',
        ),
        migrations.RemoveField(
            model_name='autotsp',
            name='notif_a',
        ),
        migrations.RemoveField(
            model_name='autotsp',
            name='tipo_notif',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='fecha_notif',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='hora_notif',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='notif_a',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='tipo_notif',
        ),
        migrations.RemoveField(
            model_name='resolucion',
            name='fecha_notif',
        ),
        migrations.RemoveField(
            model_name='resolucion',
            name='hora_notif',
        ),
        migrations.RemoveField(
            model_name='resolucion',
            name='notif_a',
        ),
        migrations.RemoveField(
            model_name='resolucion',
            name='tipo_notif',
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, verbose_name='N° Memorándum')),
                ('fecha', models.DateField(verbose_name='Fecha Memorándum')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Memorándum')),
                ('autotpe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memorandum', to='tpe_app.autotpe', verbose_name='Auto TPE')),
            ],
            options={
                'verbose_name': 'Memorándum',
                'verbose_name_plural': 'Memorándums',
                'db_table': 'memorandum',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=10, verbose_name='Tipo de Notificación')),
                ('notificado_a', models.CharField(blank=True, max_length=100, verbose_name='Notificado a / Periódico / Dirección')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora de Notificación')),
                ('autotpe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion', to='tpe_app.autotpe', verbose_name='Auto TPE')),
                ('autotsp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion', to='tpe_app.autotsp', verbose_name='Auto TSP')),
                ('recurso_tsp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion', to='tpe_app.recursotsp', verbose_name='Recurso TSP')),
                ('resolucion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion', to='tpe_app.resolucion', verbose_name='Resolución')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha'],
            },
        ),
    ]
