# Generated by Django 5.2 on 2026-05-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0004_remove_resolucion_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='estado',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('PROCESO_EN_EL_TSP', 'Proceso en el TSP'), ('CUMPLIMIENTO_EN_TPE', 'En Cumplimiento (Devuelto por TSP)'), ('PROCESO_CONCLUIDO_TPE', 'Proceso Concluido (TPE)'), ('PROCESO_CONCLUIDO_TSP_TPE', 'Proceso Concluido (TSP-TPE)'), ('PROCESO_EJECUTADO', 'Proceso Ejecutado'), ('OBSERVADO', 'Observado')], db_index=True, default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='fase',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'En Espera de RAP (plazo 3 días)'), ('EN_AGENDA_EJECUTORIA', 'En Agenda (Auto de Ejecutoria)'), ('EN_EJECUTORIA', 'Auto de Ejecutoria Emitido'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorándum Retornado (Proceso Ejecutado)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('RECIBIDO_TSP', 'Pronunciamiento TSP Recibido en TPE'), ('EN_CUMPLIMIENTO', 'Auto de Cumplimiento/Ejecutoria en Elaboración'), ('EN_AGENDA_CUMPLIMIENTO', 'Agendado para Reunión (Cumplimiento TSP)'), ('CUMPLIMIENTO_EMITIDO', 'Auto de Cumplimiento/Ejecutoria Emitido'), ('CUMPLIMIENTO_NOTIFICADO', 'Cumplimiento TSP Notificado (Pte. Archivo)'), ('CONCLUIDO_TSP_TPE', 'Archivado / Concluido (TSP-TPE)'), ('NULIDAD_TSP', 'Nulidad de Obrados por el TSP')], db_index=True, default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
    ]
