# Generated by Django 5.2.12 on 2026-03-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0004_alter_raee_options_remove_sim_sim_fectpe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abog',
            name='AB_CI',
            field=models.DecimalField(decimal_places=0, max_digits=13, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_CI',
            field=models.DecimalField(decimal_places=0, max_digits=13, unique=True, verbose_name='Cédula de Identidad'),
        ),
    ]
