# Generated by Django 5.2 on 2026-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0005_documentoadjunto_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='numero_carpeta',
            field=models.IntegerField(blank=True, help_text='Número de ubicación física de la carpeta en el archivo (ej: 40–250)', null=True, verbose_name='N° Carpeta Física'),
        ),
    ]
