# Generated by Django 5.2.12 on 2026-03-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0005_alter_abog_ab_ci_alter_pm_pm_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='PM_ARMA',
            field=models.CharField(blank=True, choices=[('INFANTERIA', 'Infantería'), ('CABALLERIA', 'Caballería'), ('ARTILLERIA', 'Artillería'), ('INGENIERIA', 'Ingeniería'), ('COMUNICACIONES', 'Comunicaciones'), ('INTENDENCIA', 'Intendencia'), ('SANIDAD', 'Sanidad'), ('TOPGRAFIA', 'TOPOGRAFIA'), ('AVIACION', 'Aviación del Ejército'), ('MUSICA', 'MÚSICA')], max_length=20, null=True, verbose_name='Arma'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_ESCALAFON',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('OFICIAL_SUPERIOR', 'Oficial Superior'), ('OFICIAL_SUBALTERNO', 'Oficial Subalterno'), ('SUBOFICIAL', 'Suboficial'), ('SARGENTO', 'Sargento'), ('TROPA', 'Tropa'), ('EMPLEADO_CIVIL', 'Empleado Civil')], max_length=20, null=True, verbose_name='Escalafón'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_GRADO',
            field=models.CharField(blank=True, choices=[('GENERAL_EJERCITO', 'General de Ejército'), ('GENERAL_DIVISION', 'General de División'), ('GENERAL_BRIGADA', 'General de Brigada'), ('CORONEL', 'Coronel'), ('TCNEL', 'Teniente Coronel'), ('MAYOR', 'Mayor'), ('CAPITAN', 'Capitán'), ('TENIENTE', 'Teniente'), ('SUBTENIENTE', 'Subteniente'), ('SUBOFICIAL_MAYOR', 'Suboficial Mayor'), ('SUBOFICIAL_MAESTRE', 'Suboficial Maestre'), ('SUBOFICIAL_1RO', 'Suboficial Primero'), ('SUBOFICIAL_2DO', 'Suboficial Segundo'), ('SUBOFICIAL_INICIAL', 'Suboficial Inicial'), ('SARGENTO_1RO', 'Sargento Primero'), ('SARGENTO_2DO', 'Sargento Segundo'), ('SARGENTO_INICIAL', 'Sargento Inicial'), ('CABO', 'Cabo'), ('DRAGONEANTE', 'Dragoneante'), ('SOLDADO', 'Soldado'), ('PROF_V', 'Prof. V'), ('PROF_IV', 'Prof. IV'), ('PROF_III', 'Prof. III'), ('PROF_II', 'Prof. II'), ('PROF_I', 'Prof. I'), ('TEC_V', 'Tec. V'), ('TEC_IV', 'Tec. IV'), ('TEC_III', 'Tec. III'), ('TEC_II', 'Tec. II'), ('TEC_I', 'Tec. I'), ('ADM_V', 'Adm. V'), ('ADM_IV', 'Adm. IV'), ('ADM_III', 'Adm. III'), ('ADM_II', 'Adm. II'), ('ADM_I', 'Adm. I'), ('APAD_V', 'Apad. V'), ('APAD_IV', 'Apad. IV'), ('APAD_III', 'Apad. III'), ('APAD_II', 'Apad. II'), ('APAD_I', 'Apad. I')], max_length=20, null=True, verbose_name='Grado'),
        ),
    ]
