# Generated by Django 5.2 on 2026-05-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0005_add_estados_fases_tsp_cumplimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorandum',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorandums', to='tpe_app.resolucion', verbose_name='Resolución vinculada'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='autotpe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorandums', to='tpe_app.autotpe', verbose_name='Auto TPE vinculado'),
        ),
    ]
