# Generated by Django 6.0.2 on 2026-04-13 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0005_vocal_tpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotpe',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Militar'),
        ),
        migrations.AddField(
            model_name='autotpe',
            name='raee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.raee', verbose_name='RAEE origen'),
        ),
        migrations.AddField(
            model_name='autotpe',
            name='rap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.rap', verbose_name='Recurso Apelación origen'),
        ),
        migrations.AddField(
            model_name='autotpe',
            name='res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.res', verbose_name='Resolución origen'),
        ),
        migrations.AddField(
            model_name='autotpe',
            name='rr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.rr', verbose_name='Recurso Reconsideración origen'),
        ),
        migrations.AddField(
            model_name='dictamen',
            name='DIC_CONCL_SEC',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusión confirmada/modificada por Secretario'),
        ),
        migrations.AddField(
            model_name='dictamen',
            name='DIC_CONFIR_FEC',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='dictamen',
            name='DIC_ESTADO',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmar'), ('CONFIRMADO', 'Confirmado sin cambios'), ('MODIFICADO', 'Modificado por secretario')], default='PENDIENTE', max_length=20, verbose_name='Estado de confirmación'),
        ),
        migrations.AddField(
            model_name='dictamen',
            name='secretario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictamenes_confirmados', to='tpe_app.vocal_tpe', verbose_name='Secretario de Actas que confirma'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='vocal',
            field=models.ForeignKey(blank=True, help_text='Solo para usuarios con rol VOCAL_TPE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.vocal_tpe', verbose_name='Vinculado a Vocal TPE'),
        ),
        migrations.AddField(
            model_name='raee',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Militar'),
        ),
        migrations.AddField(
            model_name='rap',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Militar'),
        ),
        migrations.AddField(
            model_name='res',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Militar'),
        ),
        migrations.AddField(
            model_name='rr',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Militar'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ABOGADO', 'Abogado'), ('BUSCADOR', 'Buscador'), ('ADMINISTRATIVO', 'Administrativo'), ('VOCAL_TPE', 'Vocal TPE')], max_length=20, verbose_name='Rol/Perfil'),
        ),
        migrations.AlterField(
            model_name='vocal_tpe',
            name='cargo',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('VOCAL', 'Vocal'), ('SECRETARIO_ACTAS', 'Secretario de Actas')], max_length=20, verbose_name='Cargo'),
        ),
    ]
