# Generated by Django 6.0.2 on 2026-04-15 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0006_autotpe_pm_autotpe_raee_autotpe_rap_autotpe_res_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='SIM_FASE',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'En Espera de RAP (plazo 3 días)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('EN_AGENDA_EJECUTORIA', 'En Agenda (Auto de Ejecutoria)'), ('CONCLUIDO', 'Concluido')], default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
        migrations.CreateModel(
            name='CustodiaSIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_custodio', models.CharField(choices=[('ADMIN1', 'Administrativo 1 (Agendador)'), ('ADMIN2', 'Administrativo 2 (Archivo SIM)'), ('ADMIN3', 'Administrativo 3 (Notificador)'), ('ABOG_ASESOR', 'Abogado Asesor (1ra. Resolución)'), ('ABOG_RR', 'Abogado (Recurso de Reconsideración)'), ('ABOG_AUTOS', 'Abogado Autos (Ejecutoria/Cumplimiento)'), ('ABOG_RAP', 'Abogado 3 (Búsqueda/RAP)'), ('TSP', 'Elevado al TSP (externo)'), ('ARCHIVO', 'Archivado / Concluido')], max_length=20, verbose_name='Tipo de Custodio')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('fecha_entrega', models.DateTimeField(blank=True, help_text='Null = aún en su poder', null=True, verbose_name='Fecha de Entrega')),
                ('abog', models.ForeignKey(blank=True, help_text='Si el custodio es un abogado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodias', to='tpe_app.sim', verbose_name='Sumario')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que registró la entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Custodia SIM',
                'verbose_name_plural': 'Custodias SIM',
                'db_table': 'custodia_sim',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
