# Generated by Django 5.2 on 2026-04-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0006_sim_numero_carpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Vinculado a Personal Militar'),
        ),
    ]
