# Generated by Django 6.0.3 on 2026-03-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0006_alter_pm_pm_arma_alter_pm_pm_escalafon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='PM_ARMA',
            field=models.CharField(blank=True, choices=[('INFANTERIA', 'Infantería'), ('CABALLERIA', 'Caballería'), ('ARTILLERIA', 'Artillería'), ('INGENIERIA', 'Ingeniería'), ('COMUNICACIONES', 'Comunicaciones'), ('INTENDENCIA', 'Intendencia'), ('SANIDAD', 'Sanidad'), ('TOPOGRAFIA', 'Topografía'), ('AVIACION', 'Aviación del Ejército'), ('MÚSICA', 'Música')], max_length=20, null=True, verbose_name='Arma'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='ID_ABOG',
            field=models.ForeignKey(blank=True, db_column='ID_ABOG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_ESTADO',
            field=models.CharField(choices=[('PARA AGENDA', 'PARA AGENDA'), ('PROCESO EN EL TPE.', 'Proceso en el TPE.'), ('EN APELACION_TSP', 'En Apelación TSP')], default='RADICADO_TPE', max_length=20, verbose_name='Estado del Sumario'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_TIPO',
            field=models.CharField(choices=[('DISCIPLINARIO', 'Disciplinario'), ('LETRA D', 'Letra D'), ('RESTITUCIÓN ANTIGUEDAD', 'Restición Antiguedad'), ('ASCENSO AL GRADO INMEDIATO SUPERIOR', 'Ascenso al Grado Inmediato Superior'), ('ASCENSO POSTUMO', 'Ascenso Postumo'), ('Licencia Maxima', 'Licencia Máxima')], max_length=50, verbose_name='Tipo'),
        ),
    ]
