# Generated by Django 5.2 on 2026-05-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0007_fix_cascade_to_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiasim',
            name='nombre_abogado',
            field=models.CharField(blank=True, help_text='Se completa automáticamente. Preserva el nombre si el abogado se elimina.', max_length=100, null=True, verbose_name='Nombre Abogado (histórico)'),
        ),
        migrations.AddField(
            model_name='custodiasim',
            name='nombre_abogado_destino',
            field=models.CharField(blank=True, help_text='Se completa automáticamente. Preserva el nombre si el abogado se elimina.', max_length=100, null=True, verbose_name='Nombre Abogado Destino (histórico)'),
        ),
        migrations.AlterField(
            model_name='abog_sim',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='autotpe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tpe_app.autotpe', verbose_name='Auto TPE'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='autotsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tpe_app.autotsp', verbose_name='Auto TSP'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='recurso_tsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tpe_app.recursotsp', verbose_name='Recurso TSP'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tpe_app.resolucion', verbose_name='Resolución'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tpe_app.sim', verbose_name='Sumario SIM'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='autotpe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memorandums', to='tpe_app.autotpe', verbose_name='Auto TPE vinculado'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memorandums', to='tpe_app.resolucion', verbose_name='Resolución vinculada'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='autotpe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacion', to='tpe_app.autotpe', verbose_name='Auto TPE'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='autotsp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacion', to='tpe_app.autotsp', verbose_name='Auto TSP'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='recurso_tsp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacion', to='tpe_app.recursotsp', verbose_name='Recurso TSP'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='resolucion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacion', to='tpe_app.resolucion', verbose_name='Resolución'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('MASTER', 'Master (Control Total)'), ('ADMINISTRADOR', 'Administrador de Sistemas'), ('AYUDANTE', 'Ayudante (Registro Histórico)'), ('ADMIN1_AGENDADOR', 'Administrativo 1 (Agendador)'), ('ADMIN2_ARCHIVO', 'Administrativo 2 (Archivo SIM)'), ('ADMIN3_NOTIFICADOR', 'Administrativo 3 (Notificador)'), ('ABOG1_ASESOR', 'Abogado 1 (Asesor/1ra Resolución)'), ('ABOG2_AUTOS', 'Abogado 2 (Autos de Ejecución)'), ('ABOG3_BUSCADOR', 'Abogado 3 (Búsqueda de Antecedentes)'), ('SECRETARIO_ACTAS', 'Secretario de Actas'), ('ASESOR_JEFE', 'Asesor Jefe (Supervisor de Procesos)'), ('ASESOR_JURIDICO', 'Asesor Jurídico del DPTO-I'), ('BUSCADOR', 'Buscador (General)')], max_length=20, verbose_name='Rol/Perfil'),
        ),
        migrations.AlterField(
            model_name='pm_sim',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AlterField(
            model_name='recursotsp',
            name='recurso_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aclaraciones', to='tpe_app.recursotsp', verbose_name='Recurso origen (solo ACLARACION_ENMIENDA)'),
        ),
        migrations.AddIndex(
            model_name='recursotsp',
            index=models.Index(fields=['instancia'], name='recurso_tsp_instanc_5f2e94_idx'),
        ),
        migrations.AddIndex(
            model_name='recursotsp',
            index=models.Index(fields=['sim', 'instancia'], name='recurso_tsp_sim_id_91204d_idx'),
        ),
        migrations.AddIndex(
            model_name='recursotsp',
            index=models.Index(fields=['fecha'], name='recurso_tsp_fecha_ee1324_idx'),
        ),
        migrations.AddIndex(
            model_name='recursotsp',
            index=models.Index(fields=['abogado'], name='recurso_tsp_abogado_8a3499_idx'),
        ),
        migrations.AddIndex(
            model_name='resolucion',
            index=models.Index(fields=['instancia'], name='resolucion_instanc_5b7604_idx'),
        ),
        migrations.AddIndex(
            model_name='resolucion',
            index=models.Index(fields=['sim', 'instancia'], name='resolucion_sim_id_b438be_idx'),
        ),
        migrations.AddIndex(
            model_name='resolucion',
            index=models.Index(fields=['fecha'], name='resolucion_fecha_b8667f_idx'),
        ),
        migrations.AddIndex(
            model_name='resolucion',
            index=models.Index(fields=['abogado'], name='resolucion_abogado_dca2ea_idx'),
        ),
    ]
