# Generated by Django 6.0.3 on 2026-03-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0007_alter_pm_pm_arma_alter_sim_id_abog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='SIM_ESTADO',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('EN_APELACION_TSP', 'En Apelación TSP')], default='PARA_AGENDA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_TIPO',
            field=models.CharField(choices=[('DISCIPLINARIO', 'Disciplinario'), ('LETRA D', 'Letra D'), ('RESTITUCIÓN ANTIGUEDAD', 'Restición Antiguedad'), ('ASCENSO AL GRADO INMEDIATO SUPERIOR', 'Ascenso al Grado Inmediato Superior'), ('ASCENSO POSTUMO', 'Ascenso Postumo'), ('Licencia Maxima', 'Licencia Máxima')], max_length=100, verbose_name='Tipo'),
        ),
    ]
