# Generated by Django 5.2 on 2026-04-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0007_add_pm_to_perfil_usuario'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE perfil_usuario SET rol = 'SECRETARIO_ACTAS' WHERE rol = 'VOCAL_TPE'",
            reverse_sql="UPDATE perfil_usuario SET rol = 'VOCAL_TPE' WHERE rol = 'SECRETARIO_ACTAS'",
        ),
    ]
