# Generated by Django 6.0.2 on 2026-04-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0007_sim_sim_fase_custodiasim'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='AG_ESTADO',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('SUSPENDIDA', 'Suspendida'), ('REPROGRAMADA', 'Reprogramada')], db_column='AG_ESTADO', default='PROGRAMADA', max_length=20, verbose_name='Estado de la Agenda'),
        ),
    ]
