# Generated by Django 6.0.2 on 2026-04-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0008_agenda_ag_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('MASTER', 'Master (Control Total)'), ('ADMINISTRADOR', 'Administrador de Sistemas'), ('AYUDANTE', 'Ayudante (Registro Histórico)'), ('ADMIN1_AGENDADOR', 'Administrativo 1 (Agendador)'), ('ADMIN2_ARCHIVO', 'Administrativo 2 (Archivo SIM)'), ('ADMIN3_NOTIFICADOR', 'Administrativo 3 (Notificador)'), ('ABOG1_ASESOR', 'Abogado 1 (Asesor/1ra Resolución)'), ('ABOG2_AUTOS', 'Abogado 2 (Autos de Ejecución)'), ('ABOG3_BUSCADOR', 'Abogado 3 (Búsqueda de Antecedentes)'), ('VOCAL_TPE', 'Vocal TPE (Secretario de Actas)'), ('ASESOR_JURIDICO', 'Asesor Jurídico del DPTO-I'), ('ABOGADO', 'Abogado (General)'), ('BUSCADOR', 'Buscador (General)'), ('ADMINISTRATIVO', 'Administrativo (General)')], max_length=20, verbose_name='Rol/Perfil'),
        ),
        migrations.AlterField(
            model_name='res',
            name='RES_TIPO',
            field=models.CharField(choices=[('ARCHIVO_OBRADOS', 'Archivo de Obrados'), ('ADMINISTRATIVO', 'Administrativo'), ('SANCIONES_DISCIPLINARIAS', 'Sanciones Disciplinarias'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'No ha Lugar a la Sanción Disciplinaria'), ('SANCION_ARRESTO', 'Sanción Arresto (Ejecutiva)'), ('SANCION_LETRA_B', 'Sanción Letra B (Pérdida de Antigüedad)'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('SANCION_BAJA', 'Sanción Baja'), ('SOLICITUD_LETRA_D', 'Solicitud Letra D (Permiso Médico)'), ('SOLICITUD_LICENCIA_MAXIMA', 'Solicitud Licencia Máxima'), ('SOLICITUD_ASCENSO', 'Solicitud de Ascenso'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'Solicitud de Restitución de Antigüedad'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'Solicitud de Restitución de Derechos Profesionales'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'Solicitud Artículo 114 (Invalides Instructor)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'Solicitud Artículo 117 (Fallecimiento)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'Solicitud Artículo 118 (Invalidez Sldo)'), ('OTRO', 'Otro')], max_length=100, verbose_name='Tipo'),
        ),
    ]
