# Generated by Django 5.2 on 2026-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0008_rename_rol_vocal_tpe_to_secretario_actas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocal_tpe',
            name='cargo_em',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo en Estado Mayor'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('MASTER', 'Master (Control Total)'), ('ADMINISTRADOR', 'Administrador de Sistemas'), ('AYUDANTE', 'Ayudante (Registro Histórico)'), ('ADMIN1_AGENDADOR', 'Administrativo 1 (Agendador)'), ('ADMIN2_ARCHIVO', 'Administrativo 2 (Archivo SIM)'), ('ADMIN3_NOTIFICADOR', 'Administrativo 3 (Notificador)'), ('ABOG1_ASESOR', 'Abogado 1 (Asesor/1ra Resolución)'), ('ABOG2_AUTOS', 'Abogado 2 (Autos de Ejecución)'), ('ABOG3_BUSCADOR', 'Abogado 3 (Búsqueda de Antecedentes)'), ('SECRETARIO_ACTAS', 'Secretario de Actas'), ('ASESOR_JEFE', 'Asesor Jefe (Supervisor de Procesos)'), ('ASESOR_JURIDICO', 'Asesor Jurídico del DPTO-I'), ('ABOGADO', 'Abogado (General)'), ('BUSCADOR', 'Buscador (General)')], max_length=20, verbose_name='Rol/Perfil'),
        ),
        migrations.AlterField(
            model_name='vocal_tpe',
            name='cargo',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('VOCAL', 'Vocal'), ('SECRETARIO_ACTAS', 'Secretario de Actas'), ('ASESOR_JEFE', 'Asesor Jurídico Supervisor'), ('RELATOR', 'Vocal Relator')], max_length=20, verbose_name='Cargo en Tribunal'),
        ),
    ]
