# Generated by Django 5.2 on 2026-05-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0008_fix_remaining_high_medium_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotpe',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AlterField(
            model_name='autotsp',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.agenda', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AlterField(
            model_name='recursotsp',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AddConstraint(
            model_name='recursotsp',
            constraint=models.UniqueConstraint(fields=('numero', 'instancia'), name='uniq_recurso_tsp_numero_instancia'),
        ),
    ]
