# Generated by Django 5.2.12 on 2026-03-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0008_alter_sim_sim_estado_alter_sim_sim_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_TIPO',
            field=models.CharField(choices=[('SOBRESEIDO', 'Sobreseído'), ('NULIDAD_OBRADOS', 'Nulidad de Obrados'), ('SANCION_ARRESTO', 'Sanción Arresto'), ('SANCION_LETRA_B', 'Sanción Letra B'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('AUTO_CUMPLIMIENTO', 'Auto de Cumplimiento'), ('AUTO_EJECUTORIA', 'Auto de Ejecutoria'), ('AUTO_EXCUSA', 'Auto de Excusa'), ('AUTO_RECHAZO_RECURSO', 'Auto de Rechazo de Recurso')], max_length=100, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_ESTADO',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRO OBLIGATORIO', 'Retiro Obligatorio'), ('RESERVA_ACTIVA', 'Reserva Activa'), ('BAJA', 'Baja'), ('FALLECIDO', 'Fallecido')], default='ACTIVO', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_GRADO',
            field=models.CharField(blank=True, choices=[('GENERAL_EJERCITO', 'General de Ejército'), ('GENERAL_DIVISION', 'General de División'), ('GENERAL_BRIGADA', 'General de Brigada'), ('CORONEL', 'Coronel'), ('TCNEL', 'Teniente Coronel'), ('MAYOR', 'Mayor'), ('CAPITAN', 'Capitán'), ('TENIENTE', 'Teniente'), ('SUBTENIENTE', 'Subteniente'), ('SUBOFICIAL_MAESTRE', 'Suboficial Maestre'), ('SUBOFICIAL_MAYOR', 'Suboficial Mayor'), ('SUBOFICIAL_1RO', 'Suboficial Primero'), ('SUBOFICIAL_2DO', 'Suboficial Segundo'), ('SUBOFICIAL_INICIAL', 'Suboficial Inicial'), ('SARGENTO_1RO', 'Sargento Primero'), ('SARGENTO_2DO', 'Sargento Segundo'), ('SARGENTO_INICIAL', 'Sargento Inicial'), ('CABO', 'Cabo'), ('DRAGONEANTE', 'Dragoneante'), ('SOLDADO', 'Soldado'), ('PROF_V', 'Prof. V'), ('PROF_IV', 'Prof. IV'), ('PROF_III', 'Prof. III'), ('PROF_II', 'Prof. II'), ('PROF_I', 'Prof. I'), ('TEC_V', 'Tec. V'), ('TEC_IV', 'Tec. IV'), ('TEC_III', 'Tec. III'), ('TEC_II', 'Tec. II'), ('TEC_I', 'Tec. I'), ('ADM_V', 'Adm. V'), ('ADM_IV', 'Adm. IV'), ('ADM_III', 'Adm. III'), ('ADM_II', 'Adm. II'), ('ADM_I', 'Adm. I'), ('APAD_V', 'Apad. V'), ('APAD_IV', 'Apad. IV'), ('APAD_III', 'Apad. III'), ('APAD_II', 'Apad. II'), ('APAD_I', 'Apad. I')], max_length=20, null=True, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='res',
            name='RES_TIPO',
            field=models.CharField(choices=[('SANCIONES_DISCIPLINARIAS', 'Sanciones Disciplinarias'), ('SANCION_ARRESTO', 'Sanción Arresto (Ejecutiva)'), ('SANCION_LETRA_B', 'Sanción Letra B (Pérdida de Antigüedad)'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('SANCION_BAJA', 'Sanción Baja'), ('SOLICITUD_LETRA_D', 'Solicitud Letra D (Permiso Médico)'), ('SOLICITUD_LICENCIA_MAXIMA', 'Solicitud Licencia Máxima'), ('SOLICITUD_ASCENSO', 'Solicitud de Ascenso'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'Solicitud de Restitución de Antigüedad'), ('ARCHIVO_OBRADOS', 'Archivo de Obrados'), ('SOLICITUD_ART_114_LOFA', 'Solicitud Artículo 114 LOFA'), ('OTRO', 'Otro')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_TIPO',
            field=models.CharField(choices=[('DISCIPLINARIO', 'Disciplinario'), ('LETRA D', 'Letra D'), ('RESTITUCIÓN ANTIGUEDAD', 'Restición Antiguedad'), ('ASCENSO AL GRADO INMEDIATO SUPERIOR', 'Ascenso al Grado Inmediato Superior'), ('ASCENSO POSTUMO', 'Ascenso Postumo'), ('Licencia Maxima', 'Licencia Máxima'), ('Art. 114 LOFA', 'Artículo 114 LOFA')], max_length=100, verbose_name='Tipo'),
        ),
    ]
