# Generated by Django 6.0.3 on 2026-03-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0009_alter_autotpe_tpe_tipo_alter_pm_pm_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abog',
            name='AB_CI',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, verbose_name='Cédula de Identidad'),
        ),
    ]
