# Generated by Django 6.0.2 on 2026-04-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0009_alter_perfilusuario_rol_alter_res_res_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='abog_sim',
            name='es_responsable',
            field=models.BooleanField(default=False, help_text='El responsable custodia la carpeta física y puede entregarla', verbose_name='Responsable de carpeta'),
        ),
    ]
