# Generated by Django 6.0.3 on 2026-03-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0010_alter_abog_ab_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotpe',
            name='TPE_EJECU_FECNOT',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='TPE_EJECU_NOT',
        ),
    ]
