# Generated by Django 5.2 on 2026-05-05 19:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0010_add_audit_trail_axes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoadjunto',
            name='autotsp',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='autotsp',
        ),
        migrations.RemoveField(
            model_name='historicalrecursotsp',
            name='abogado',
        ),
        migrations.RemoveField(
            model_name='historicalrecursotsp',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrecursotsp',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='historicalrecursotsp',
            name='recurso_origen',
        ),
        migrations.RemoveField(
            model_name='historicalrecursotsp',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='historicalrecursotsp',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='abogado',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='recurso_origen',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='recursotsp',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='historicalautotpe',
            name='recurso_tsp',
        ),
        migrations.RemoveField(
            model_name='documentoadjunto',
            name='recurso_tsp',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='recurso_tsp',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='recurso_tsp',
        ),
        migrations.CreateModel(
            name='ActuadoTSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.CharField(choices=[('RAEE', 'Aclaración, Explicación y Enmienda'), ('NULIDAD', 'Nulidad de Obrados'), ('AUTO_TSP', 'Auto del TSP')], max_length=20, verbose_name='Tipo de Actuado TSP')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número del Actuado TSP')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Parte Resolutiva')),
                ('tipo', models.CharField(blank=True, choices=[('CONFIRMAR', 'CONFIRMAR'), ('REVOCAR', 'REVOCAR'), ('MODIFICAR', 'MODIFICAR'), ('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('CONFIRMA_SANCION', 'CONFIRMA SANCIÓN'), ('REDUCE_SANCION', 'REDUCE SANCIÓN'), ('REVOCA_SANCION', 'REVOCA SANCIÓN'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('OTRO', 'OTRO')], max_length=50, null=True, verbose_name='Tipo de Resolución TSP')),
                ('es_pronunciamiento_final', models.BooleanField(default=False, help_text='Al activar, el sistema registrará que el TSP devolvió el caso al TPE para cumplimiento.', verbose_name='¿Es el pronunciamiento final del TSP?')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'Actuado del TSP',
                'verbose_name_plural': 'Actuados del TSP',
                'db_table': 'actuado_tsp',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='actuado_tsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tpe_app.actuadotsp', verbose_name='Actuado TSP'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='actuado_tsp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacion', to='tpe_app.actuadotsp', verbose_name='Actuado TSP'),
        ),
        migrations.CreateModel(
            name='ApelacionTSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número del RAP')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto del Recurso')),
                ('tipo', models.CharField(blank=True, choices=[('REVOCAR', 'REVOCAR'), ('MODIFICAR', 'MODIFICAR'), ('ANULAR HASTA EL VICIO MAS ANTIGUO', 'ANULAR HASTA EL VICIO MAS ANTIGUO'), ('OTRO', 'OTRO')], max_length=50, null=True, verbose_name='Petitorio (lo que solicita al TSP)')),
                ('numero_oficio', models.CharField(blank=True, max_length=60, null=True, verbose_name='N° Oficio Elevación')),
                ('fecha_oficio', models.DateField(blank=True, null=True, verbose_name='Fecha del Oficio')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite 3 días hábiles')),
                ('abogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apelaciones_tsp_como_abogado', to='tpe_app.pm', verbose_name='Abogado')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apelaciones_tsp_como_recurrente', to='tpe_app.pm', verbose_name='Recurrente')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.resolucion', verbose_name='Resolución impugnada')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'Apelación al TSP (RAP)',
                'verbose_name_plural': 'Apelaciones al TSP (RAP)',
                'db_table': 'apelacion_tsp',
                'ordering': ['-fecha_presentacion'],
            },
        ),
        migrations.AddField(
            model_name='actuadotsp',
            name='apelacion_tsp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actuados', to='tpe_app.apelaciontsp', verbose_name='Apelación TSP origen'),
        ),
        migrations.AddField(
            model_name='autotpe',
            name='apelacion_tsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.apelaciontsp', verbose_name='Apelación TSP origen'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='apelacion_tsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tpe_app.apelaciontsp', verbose_name='Apelación TSP (RAP)'),
        ),
        migrations.AddField(
            model_name='historicalautotpe',
            name='apelacion_tsp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.apelaciontsp', verbose_name='Apelación TSP origen'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='apelacion_tsp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacion', to='tpe_app.apelaciontsp', verbose_name='Apelación TSP (RAP)'),
        ),
        migrations.CreateModel(
            name='HistoricalActuadoTSP',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('instancia', models.CharField(choices=[('RAEE', 'Aclaración, Explicación y Enmienda'), ('NULIDAD', 'Nulidad de Obrados'), ('AUTO_TSP', 'Auto del TSP')], max_length=20, verbose_name='Tipo de Actuado TSP')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número del Actuado TSP')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Parte Resolutiva')),
                ('tipo', models.CharField(blank=True, choices=[('CONFIRMAR', 'CONFIRMAR'), ('REVOCAR', 'REVOCAR'), ('MODIFICAR', 'MODIFICAR'), ('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('CONFIRMA_SANCION', 'CONFIRMA SANCIÓN'), ('REDUCE_SANCION', 'REDUCE SANCIÓN'), ('REVOCA_SANCION', 'REVOCA SANCIÓN'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('OTRO', 'OTRO')], max_length=50, null=True, verbose_name='Tipo de Resolución TSP')),
                ('es_pronunciamiento_final', models.BooleanField(default=False, help_text='Al activar, el sistema registrará que el TSP devolvió el caso al TPE para cumplimiento.', verbose_name='¿Es el pronunciamiento final del TSP?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('apelacion_tsp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.apelaciontsp', verbose_name='Apelación TSP origen')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sim', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'historical Actuado del TSP',
                'verbose_name_plural': 'historical Actuados del TSP',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalApelacionTSP',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número del RAP')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto del Recurso')),
                ('tipo', models.CharField(blank=True, choices=[('REVOCAR', 'REVOCAR'), ('MODIFICAR', 'MODIFICAR'), ('ANULAR HASTA EL VICIO MAS ANTIGUO', 'ANULAR HASTA EL VICIO MAS ANTIGUO'), ('OTRO', 'OTRO')], max_length=50, null=True, verbose_name='Petitorio (lo que solicita al TSP)')),
                ('numero_oficio', models.CharField(blank=True, max_length=60, null=True, verbose_name='N° Oficio Elevación')),
                ('fecha_oficio', models.DateField(blank=True, null=True, verbose_name='Fecha del Oficio')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite 3 días hábiles')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('abogado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.pm', verbose_name='Abogado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.pm', verbose_name='Recurrente')),
                ('resolucion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.resolucion', verbose_name='Resolución impugnada')),
                ('sim', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'historical Apelación al TSP (RAP)',
                'verbose_name_plural': 'historical Apelaciones al TSP (RAP)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='AUTOTSP',
        ),
        migrations.DeleteModel(
            name='HistoricalRecursoTSP',
        ),
        migrations.DeleteModel(
            name='RecursoTSP',
        ),
        migrations.AddIndex(
            model_name='apelaciontsp',
            index=models.Index(fields=['sim'], name='apelacion_t_sim_id_a035fd_idx'),
        ),
        migrations.AddIndex(
            model_name='apelaciontsp',
            index=models.Index(fields=['pm'], name='apelacion_t_pm_id_3fae14_idx'),
        ),
        migrations.AddIndex(
            model_name='apelaciontsp',
            index=models.Index(fields=['fecha_presentacion'], name='apelacion_t_fecha_p_e58fba_idx'),
        ),
    ]
