# Generated by Django 6.0.2 on 2026-04-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0010_add_es_responsable_abog_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiasim',
            name='fecha_oficio',
            field=models.DateField(blank=True, help_text='Fecha de emisión del oficio al TSP', null=True, verbose_name='Fecha del Oficio (TSP)'),
        ),
        migrations.AddField(
            model_name='custodiasim',
            name='motivo',
            field=models.CharField(blank=True, choices=[('AGENDA', 'Para agenda del tribunal'), ('REVISION', 'Revisión del abogado'), ('NOTIFICACION', 'Para notificación'), ('APELACION_TSP', 'Elevado al TSP'), ('ARCHIVO', 'Archivado / Concluido')], max_length=20, null=True, verbose_name='Motivo de la custodia'),
        ),
        migrations.AddField(
            model_name='custodiasim',
            name='nro_oficio',
            field=models.CharField(blank=True, help_text='Ej: OF-025/26 — solo para TSP', max_length=30, null=True, verbose_name='Número de Oficio (TSP)'),
        ),
    ]
