# Generated by Django 6.0.2 on 2026-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0011_custodiasim_fecha_oficio_custodiasim_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rr',
            name='RR_TIPO',
            field=models.CharField(blank=True, choices=[('PROCEDENCIA', 'Procedencia a su Recurso de Reconsideración'), ('IMPROCEDENCIA', 'Improcedencia a su Recurso de Reconsideración')], max_length=20, null=True, verbose_name='Tipo de Recurso'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='PM_ARMA',
            field=models.CharField(blank=True, choices=[('INF.', 'INF.'), ('CAB.', 'CAB.'), ('ART.', 'ART.'), ('ING.', 'ING.'), ('COM.', 'COM.'), ('LOG.', 'LOG.'), ('M.B.', 'M.B.'), ('INT.', 'INT.'), ('SAN.', 'SAN.'), ('TGRAFO.', 'TGRAFO.'), ('AV.', 'AV.'), ('MÚS.', 'MÚS.')], max_length=20, null=True, verbose_name='Arma'),
        ),
    ]
