# Generated by Django 5.2 on 2026-05-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0011_restructura_tsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuadotsp',
            name='apelacion_tsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actuados', to='tpe_app.apelaciontsp', verbose_name='Apelación TSP origen'),
        ),
        migrations.AlterField(
            model_name='actuadotsp',
            name='instancia',
            field=models.CharField(choices=[('RAEE', 'ACLARACIÓN, EXPLICACIÓN Y ENMIENDA (RAEE)'), ('NULIDAD', 'NULIDAD DE OBRADOS'), ('NULIDAD_DEFECTOS_ABSOLUTOS', 'NULIDAD POR DEFECTOS ABSOLUTOS'), ('AUTO_TSP', 'AUTO DEL TSP')], max_length=30, verbose_name='Tipo de Actuado TSP'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='historicalactuadotsp',
            name='instancia',
            field=models.CharField(choices=[('RAEE', 'ACLARACIÓN, EXPLICACIÓN Y ENMIENDA (RAEE)'), ('NULIDAD', 'NULIDAD DE OBRADOS'), ('NULIDAD_DEFECTOS_ABSOLUTOS', 'NULIDAD POR DEFECTOS ABSOLUTOS'), ('AUTO_TSP', 'AUTO DEL TSP')], max_length=30, verbose_name='Tipo de Actuado TSP'),
        ),
        migrations.AlterField(
            model_name='historicalautotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='historicalresolucion',
            name='instancia',
            field=models.CharField(choices=[('PRIMERA', 'PRIMERA RESOLUCIÓN'), ('RECONSIDERACION', 'RECURSO DE RECONSIDERACIÓN')], default='PRIMERA', max_length=20, verbose_name='Instancia'),
        ),
        migrations.AlterField(
            model_name='historicalresolucion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ARCHIVO_OBRADOS', 'ARCHIVO DE OBRADOS'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('SANCIONES_DISCIPLINARIAS', 'SANCIONES DISCIPLINARIAS'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'NO HA LUGAR A LA SANCIÓN DISCIPLINARIA'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO (EJECUTIVA)'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B (PÉRDIDA DE ANTIGÜEDAD)'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('SANCION_BAJA', 'SANCIÓN BAJA'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D (PERMISO MÉDICO)'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MÁXIMA'), ('SOLICITUD_ASCENSO', 'SOLICITUD DE ASCENSO'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD DE RESTITUCIÓN DE ANTIGÜEDAD'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('OTRO', 'OTRO'), ('PROCEDENCIA', 'PROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('IMPROCEDENCIA', 'IMPROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN')], max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('FIRMA', 'FIRMA'), ('EDICTO', 'EDICTO'), ('CEDULON', 'CEDULÓN')], max_length=10, verbose_name='Tipo de Notificación'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='instancia',
            field=models.CharField(choices=[('PRIMERA', 'PRIMERA RESOLUCIÓN'), ('RECONSIDERACION', 'RECURSO DE RECONSIDERACIÓN')], default='PRIMERA', max_length=20, verbose_name='Instancia'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ARCHIVO_OBRADOS', 'ARCHIVO DE OBRADOS'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('SANCIONES_DISCIPLINARIAS', 'SANCIONES DISCIPLINARIAS'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'NO HA LUGAR A LA SANCIÓN DISCIPLINARIA'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO (EJECUTIVA)'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B (PÉRDIDA DE ANTIGÜEDAD)'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('SANCION_BAJA', 'SANCIÓN BAJA'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D (PERMISO MÉDICO)'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MÁXIMA'), ('SOLICITUD_ASCENSO', 'SOLICITUD DE ASCENSO'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD DE RESTITUCIÓN DE ANTIGÜEDAD'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('OTRO', 'OTRO'), ('PROCEDENCIA', 'PROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('IMPROCEDENCIA', 'IMPROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN')], max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
