# Generated by Django 6.0.3 on 2026-03-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0011_remove_autotpe_tpe_ejecu_fecnot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotpe',
            name='TPE_EDICTO_FEC',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='TPE_EDICTO_PERIOD',
        ),
        migrations.AddField(
            model_name='autotpe',
            name='TPE_TIPO_NOTIF',
            field=models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo de Notificación'),
        ),
    ]
