# Generated by Django 6.0.2 on 2026-04-18 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0012_rr_rr_tipo_alter_pm_pm_arma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='RES_TIPO',
            field=models.CharField(choices=[('ARCHIVO_OBRADOS', 'Archivo de Obrados'), ('ADMINISTRATIVO', 'Administrativo'), ('SANCIONES_DISCIPLINARIAS', 'Sanciones Disciplinarias'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'No ha Lugar a la Sanción Disciplinaria'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'Solicitud de Retiro Voluntario'), ('SANCION_ARRESTO', 'Sanción Arresto (Ejecutiva)'), ('SANCION_LETRA_B', 'Sanción Letra B (Pérdida de Antigüedad)'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('SANCION_BAJA', 'Sanción Baja'), ('SOLICITUD_LETRA_D', 'Solicitud Letra D (Permiso Médico)'), ('SOLICITUD_LICENCIA_MAXIMA', 'Solicitud Licencia Máxima'), ('SOLICITUD_ASCENSO', 'Solicitud de Ascenso'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'Solicitud de Restitución de Antigüedad'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'Solicitud de Restitución de Derechos Profesionales'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'Solicitud Artículo 114 (Invalides Instructor)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'Solicitud Artículo 117 (Fallecimiento)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'Solicitud Artículo 118 (Invalidez Sldo)'), ('OTRO', 'Otro')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_TIPO',
            field=models.CharField(choices=[('DISCIPLINARIO', 'DISCIPLINARIO'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('ASCENSO POSTUMO', 'ASCENSO POSTUMO'), ('SOLICITUD DE RETIRO VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MAXIMA'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD RESTITUCIÓN ANTIGUEDAD'), ('SOLICITUD_DE_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ASCENSO_AL_GRADO_INMEDIATO_SUPERIOR', 'SOLICITUD ASCENSO AL GRADO INMEDIATO SUPERIOR'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RES_INSTANCIA', models.CharField(choices=[('PRIMERA', 'Primera Resolución'), ('RECONSIDERACION', 'Recurso de Reconsideración')], default='PRIMERA', max_length=20, verbose_name='Instancia')),
                ('RES_NUM', models.CharField(max_length=15, verbose_name='Número de Resolución')),
                ('RES_FEC', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('RES_RESOL', models.TextField(blank=True, null=True, verbose_name='Resolución')),
                ('RES_TIPO', models.CharField(blank=True, choices=[('ARCHIVO_OBRADOS', 'Archivo de Obrados'), ('ADMINISTRATIVO', 'Administrativo'), ('SANCIONES_DISCIPLINARIAS', 'Sanciones Disciplinarias'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'No ha Lugar a la Sanción Disciplinaria'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'Solicitud de Retiro Voluntario'), ('SANCION_ARRESTO', 'Sanción Arresto (Ejecutiva)'), ('SANCION_LETRA_B', 'Sanción Letra B (Pérdida de Antigüedad)'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('SANCION_BAJA', 'Sanción Baja'), ('SOLICITUD_LETRA_D', 'Solicitud Letra D (Permiso Médico)'), ('SOLICITUD_LICENCIA_MAXIMA', 'Solicitud Licencia Máxima'), ('SOLICITUD_ASCENSO', 'Solicitud de Ascenso'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'Solicitud de Restitución de Antigüedad'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'Solicitud de Restitución de Derechos Profesionales'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'Solicitud Artículo 114 (Invalides Instructor)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'Solicitud Artículo 117 (Fallecimiento)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'Solicitud Artículo 118 (Invalidez Sldo)'), ('OTRO', 'Otro')], max_length=100, null=True, verbose_name='Tipo (PRIMERA)')),
                ('RES_RESUM', models.CharField(blank=True, choices=[('PROCEDENCIA', 'Procedencia a su Recurso de Reconsideración'), ('IMPROCEDENCIA', 'Improcedencia a su Recurso de Reconsideración')], max_length=20, null=True, verbose_name='Resumen (RECONSIDERACION)')),
                ('RES_FECPRESEN', models.DateField(blank=True, null=True, verbose_name='Fecha Presentación (RECONSIDERACION)')),
                ('RES_FECLIMITE', models.DateField(blank=True, null=True, verbose_name='Fecha Límite 15 días (RECONSIDERACION)')),
                ('RES_TIPO_NOTIF', models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo Notificación')),
                ('RES_NOT', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico')),
                ('RES_FECNOT', models.DateField(blank=True, null=True, verbose_name='Fecha Notificación')),
                ('RES_HORNOT', models.TimeField(blank=True, null=True, verbose_name='Hora Notificación')),
                ('abog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda')),
                ('dictamen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.dictamen', verbose_name='Dictamen origen (solo PRIMERA)')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Militar')),
                ('resolucion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_reconsideracion', to='tpe_app.resolucion', verbose_name='Resolución impugnada (solo RECONSIDERACION)')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
                'db_table': 'resolucion',
                'ordering': ['-RES_FEC'],
            },
        ),
        migrations.CreateModel(
            name='RecursoTSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TSP_INSTANCIA', models.CharField(choices=[('APELACION', 'Recurso de Apelación'), ('ACLARACION_ENMIENDA', 'Aclaración, Explicación y Enmienda')], default='APELACION', max_length=25, verbose_name='Instancia')),
                ('TSP_FECPRESEN', models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación')),
                ('TSP_OFI', models.CharField(blank=True, max_length=25, null=True, verbose_name='N° Oficio Elevación')),
                ('TSP_FECOFI', models.DateField(blank=True, null=True, verbose_name='Fecha del Oficio')),
                ('TSP_FECLIMITE', models.DateField(blank=True, null=True, verbose_name='Fecha Límite 3 días (APELACION)')),
                ('TSP_TIPO', models.CharField(blank=True, choices=[('REVOCAR', 'REVOCAR'), ('CONFIRMAR', 'CONFIRMAR'), ('MODIFICAR', 'MODIFICAR'), ('ANULAR HASTA EL VICIO MAS ANTIGUO', 'ANULAR HASTA EL VICIO MAS ANTIGUO'), ('OTRO', 'OTRO')], max_length=50, null=True, verbose_name='Tipo Resolución TSP (APELACION)')),
                ('TSP_RESUM', models.CharField(blank=True, max_length=200, null=True, verbose_name='Resumen (ACLARACION_ENMIENDA)')),
                ('TSP_NUM', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número Resolución TSP')),
                ('TSP_FEC', models.DateField(blank=True, null=True, verbose_name='Fecha Resolución TSP')),
                ('TSP_RESOL', models.TextField(blank=True, null=True, verbose_name='Resolución TSP')),
                ('TSP_TIPO_NOTIF', models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo Notificación')),
                ('TSP_NOT', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico')),
                ('TSP_FECNOT', models.DateField(blank=True, null=True, verbose_name='Fecha Notificación')),
                ('TSP_HORNOT', models.TimeField(blank=True, null=True, verbose_name='Hora Notificación')),
                ('abog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.pm', verbose_name='Militar')),
                ('recurso_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aclaraciones', to='tpe_app.recursotsp', verbose_name='Recurso origen (solo ACLARACION_ENMIENDA)')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.resolucion', verbose_name='Resolución impugnada (solo APELACION)')),
            ],
            options={
                'verbose_name': 'Recurso TSP',
                'verbose_name_plural': 'Recursos TSP',
                'db_table': 'recurso_tsp',
                'ordering': ['-TSP_FEC'],
            },
        ),
    ]
