# Generated by Django 6.0.3 on 2026-03-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0012_remove_autotpe_tpe_edicto_fec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotsp',
            name='TSP_EDICTO_FEC',
        ),
        migrations.RemoveField(
            model_name='autotsp',
            name='TSP_EDICTO_PERIOD',
        ),
        migrations.RemoveField(
            model_name='res',
            name='RES_EDICTO_FEC',
        ),
        migrations.RemoveField(
            model_name='res',
            name='RES_EDICTO_PERIOD',
        ),
        migrations.AddField(
            model_name='autotsp',
            name='TSP_TIPO_NOTIF',
            field=models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo de Notificación'),
        ),
        migrations.AddField(
            model_name='raee',
            name='RAE_TIPO_NOTIF',
            field=models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo de Notificación'),
        ),
        migrations.AddField(
            model_name='rap',
            name='RAP_TIPO_NOTIF',
            field=models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo de Notificación'),
        ),
        migrations.AddField(
            model_name='res',
            name='RES_TIPO_NOTIF',
            field=models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo de Notificación'),
        ),
        migrations.AddField(
            model_name='rr',
            name='RR_TIPO_NOTIF',
            field=models.CharField(blank=True, choices=[('FIRMA', 'Firma'), ('EDICTO', 'Edicto'), ('CEDULON', 'Cedulón')], max_length=20, null=True, verbose_name='Tipo de Notificación'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_NOT',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico'),
        ),
        migrations.AlterField(
            model_name='autotsp',
            name='TSP_NOT',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico'),
        ),
        migrations.AlterField(
            model_name='raee',
            name='RAE_NOT',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico'),
        ),
        migrations.AlterField(
            model_name='rap',
            name='RAP_NOT',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico'),
        ),
        migrations.AlterField(
            model_name='res',
            name='RES_NOT',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico'),
        ),
        migrations.AlterField(
            model_name='rr',
            name='RR_NOT',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notificado a /Dirección/Periódico'),
        ),
    ]
