# Generated by Django 5.2 on 2026-05-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0012_alter_actuadotsp_apelacion_tsp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuadotsp',
            name='instancia',
            field=models.CharField(choices=[('RAP', 'RECURSO DE APELACIÓN'), ('RAEE', 'RECURSO DE ACLARACIÓN, EXPLICACIÓN Y ENMIENDA'), ('NULIDAD', 'RECURSO DE NULIDAD'), ('AUTO_TSP', 'AUTO DEL TSP')], max_length=30, verbose_name='Tipo de Actuado TSP'),
        ),
        migrations.AlterField(
            model_name='historicalactuadotsp',
            name='instancia',
            field=models.CharField(choices=[('RAP', 'RECURSO DE APELACIÓN'), ('RAEE', 'RECURSO DE ACLARACIÓN, EXPLICACIÓN Y ENMIENDA'), ('NULIDAD', 'RECURSO DE NULIDAD'), ('AUTO_TSP', 'AUTO DEL TSP')], max_length=30, verbose_name='Tipo de Actuado TSP'),
        ),
    ]
