# Generated by Django 5.2 on 2026-05-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0013_alter_actuadotsp_instancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECUSA', 'AUTO DE RECUSA'), ('AUTO_ACLARATORIO', 'AUTO ACLARATORIO'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='historicalautotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECUSA', 'AUTO DE RECUSA'), ('AUTO_ACLARATORIO', 'AUTO ACLARATORIO'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
    ]
