# Generated by Django 5.2.12 on 2026-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0013_remove_autotsp_tsp_edicto_fec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='SIM_ESTADO',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('EN_APELACION_TSP', 'En Apelación TSP')], default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
    ]
