# Generated by Django 6.0.2 on 2026-04-18 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0013_alter_res_res_tipo_alter_sim_sim_tipo_resolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotpe',
            name='recurso_tsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.recursotsp', verbose_name='Recurso TSP origen (APELACION o ACLARACION_ENMIENDA)'),
        ),
        migrations.AddField(
            model_name='autotpe',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.resolucion', verbose_name='Resolución origen (PRIMERA o RECONSIDERACION)'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='DOC_TABLA',
            field=models.CharField(choices=[('sim', 'Sumario SIM'), ('resolucion', 'Resolución (PRIMERA/RECONSIDERACION)'), ('recurso_tsp', 'Recurso TSP (APELACION/ACLARACION_ENMIENDA)'), ('autotpe', 'Auto TPE'), ('autotsp', 'Auto TSP')], max_length=30, verbose_name='Tabla de origen'),
        ),
    ]
