# Generated by Django 5.2 on 2026-05-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0014_alter_autotpe_tipo_alter_historicalautotpe_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apelaciontsp',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='apelaciontsp',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalapelaciontsp',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='historicalapelaciontsp',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='apelaciontsp',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, verbose_name='Número del RAP'),
        ),
        migrations.AlterField(
            model_name='historicalapelaciontsp',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, verbose_name='Número del RAP'),
        ),
    ]
