# Generated by Django 6.0.2 on 2026-04-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0014_autotpe_recurso_tsp_autotpe_resolucion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotpe',
            name='raee',
        ),
        migrations.RemoveField(
            model_name='rap',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='rap',
            name='rr',
        ),
        migrations.RemoveField(
            model_name='rap',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='rap',
        ),
        migrations.RemoveField(
            model_name='res',
            name='abog',
        ),
        migrations.RemoveField(
            model_name='res',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='res',
            name='dictamen',
        ),
        migrations.RemoveField(
            model_name='res',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='res',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='rr',
            name='res',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='res',
        ),
        migrations.RemoveField(
            model_name='rr',
            name='abog',
        ),
        migrations.RemoveField(
            model_name='rr',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='rr',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='rr',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='autotpe',
            name='rr',
        ),
        migrations.DeleteModel(
            name='RAEE',
        ),
        migrations.DeleteModel(
            name='RAP',
        ),
        migrations.DeleteModel(
            name='RES',
        ),
        migrations.DeleteModel(
            name='RR',
        ),
    ]
