# Generated by Django 5.2.12 on 2026-03-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0015_alter_sim_sim_resum_alter_sim_sim_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='ID_ABOG',
        ),
        migrations.AddField(
            model_name='autotpe',
            name='ID_ABOG',
            field=models.ForeignKey(blank=True, db_column='ID_ABOG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
        ),
        migrations.AddField(
            model_name='res',
            name='ID_ABOG',
            field=models.ForeignKey(blank=True, db_column='ID_ABOG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
        ),
        migrations.AddField(
            model_name='rr',
            name='ID_ABOG',
            field=models.ForeignKey(blank=True, db_column='ID_ABOG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
        ),
        migrations.AlterField(
            model_name='res',
            name='RES_TIPO',
            field=models.CharField(choices=[('ARCHIVO_OBRADOS', 'Archivo de Obrados'), ('ADMINISTRATIVO', 'Administrativo'), ('SANCIONES_DISCIPLINARIAS', 'Sanciones Disciplinarias'), ('SANCION_ARRESTO', 'Sanción Arresto (Ejecutiva)'), ('SANCION_LETRA_B', 'Sanción Letra B (Pérdida de Antigüedad)'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('SANCION_BAJA', 'Sanción Baja'), ('SOLICITUD_LETRA_D', 'Solicitud Letra D (Permiso Médico)'), ('SOLICITUD_LICENCIA_MAXIMA', 'Solicitud Licencia Máxima'), ('SOLICITUD_ASCENSO', 'Solicitud de Ascenso'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'Solicitud de Restitución de Antigüedad'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'Solicitud de Restitución de Derechos Profesionales'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'Solicitud Artículo 114 (Invalides Instructor)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'Solicitud Artículo 117 (Fallecimiento)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'Solicitud Artículo 118 (Invalidez Sldo)'), ('OTRO', 'Otro')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_ESTADO',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('EN_APELACION_TSP', 'En Apelación TSP'), ('CONCLUIDO', 'Concluido')], default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_RESUM',
            field=models.CharField(help_text='Breve descripción del caso (máx. 20 caracteres)', max_length=200, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_TIPO',
            field=models.CharField(choices=[('DISCIPLINARIO', 'DISCIPLINARIO'), ('ASCENSO POSTUMO', 'ASCENSO POSTUMO'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MAXIMA'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD RESTITUCIÓN ANTIGUEDAD'), ('SOLICITUD_DE_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ASCENSO_AL_GRADO_INMEDIATO_SUPERIOR', 'SOLICITUD ASCENSO AL GRADO INMEDIATO SUPERIOR'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)')], max_length=100, verbose_name='Tipo'),
        ),
    ]
