# Generated by Django 6.0.2 on 2026-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0015_remove_autotpe_raee_remove_rap_pm_remove_rap_rr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiasim',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('PENDIENTE_CONFIRMACION', 'Pendiente de Confirmación')], default='ACTIVA', max_length=25, verbose_name='Estado de la Custodia'),
        ),
    ]
