# Generated by Django 5.2 on 2026-05-10 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0015_remove_apelacion_texto_tipo_alter_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuadotsp',
            name='apelacion_tsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actuados', to='tpe_app.apelaciontsp', verbose_name='Recurso de Apelación de origen'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ORDINARIA', 'Sesión Ordinaria'), ('EXTRAORDINARIA', 'Sesión Extraordinaria'), ('COMPLEMENTARIA', 'Sesión Complementaria')], max_length=50, null=True, verbose_name='Tipo de Agenda'),
        ),
        migrations.AlterField(
            model_name='historicalactuadotsp',
            name='apelacion_tsp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.apelaciontsp', verbose_name='Recurso de Apelación de origen'),
        ),
        migrations.AlterField(
            model_name='historicalresolucion',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número de Resolución'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Número de Resolución'),
        ),
    ]
