# Generated by Django 5.2.12 on 2026-03-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0016_remove_sim_id_abog_autotpe_id_abog_res_id_abog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res',
            name='RES_RESUM',
        ),
    ]
