# Generated by Django 5.2 on 2026-05-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0016_resolucion_numero_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='abog_sim',
            name='agenda',
            field=models.ForeignKey(blank=True, help_text='Agenda en la que se agendó este sumario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECUSA', 'AUTO DE RECUSA'), ('AUTO_ACLARATORIO', 'AUTO ACLARATORIO'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO'), ('AUTO_FACULTAD', 'AUTO DE FACULTAD')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='historicalautotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECUSA', 'AUTO DE RECUSA'), ('AUTO_ACLARATORIO', 'AUTO ACLARATORIO'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO'), ('AUTO_FACULTAD', 'AUTO DE FACULTAD')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='historicalresolucion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ARCHIVO_OBRADOS', 'ARCHIVO DE OBRADOS'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('SANCIONES_DISCIPLINARIAS', 'SANCIONES DISCIPLINARIAS'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'NO HA LUGAR A LA SANCIÓN DISCIPLINARIA'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO (EJECUTIVA)'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B (PÉRDIDA DE ANTIGÜEDAD)'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('SANCION_BAJA', 'SANCIÓN BAJA'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D (PERMISO MÉDICO)'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MÁXIMA'), ('SOLICITUD_ASCENSO', 'SOLICITUD DE ASCENSO'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD DE RESTITUCIÓN DE ANTIGÜEDAD'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('OTRO', 'OTRO'), ('PROCEDENCIA', 'PROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('IMPROCEDENCIA', 'IMPROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('POSESION', 'POSESIÓN DEL TPE'), ('CIERRE', 'CIERRE DEL TPE')], max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalsim',
            name='estado',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('PROCESO_EN_EL_TSP', 'Proceso en el TSP'), ('CUMPLIMIENTO_EN_TPE', 'En Cumplimiento (Devuelto por TSP)'), ('PROCESO_CONCLUIDO_TPE', 'Proceso Concluido (TPE)'), ('PROCESO_CONCLUIDO_TSP_TPE', 'Proceso Concluido (TSP-TPE)'), ('PROCESO_EJECUTADO', 'Proceso Ejecutado'), ('OBSERVADO', 'Observado'), ('INSTITUCIONAL_VIGENTE', 'Vigente (Institucional)'), ('INSTITUCIONAL_CONCLUIDO', 'Concluido (Institucional)')], db_index=True, default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalsim',
            name='fase',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'En Espera de RAP (plazo 3 días)'), ('EN_AGENDA_EJECUTORIA', 'En Agenda (Auto de Ejecutoria)'), ('EN_EJECUTORIA', 'Auto de Ejecutoria Emitido'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorándum Retornado (Proceso Ejecutado)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('RECIBIDO_TSP', 'Pronunciamiento TSP Recibido en TPE'), ('EN_CUMPLIMIENTO', 'Auto de Cumplimiento/Ejecutoria en Elaboración'), ('EN_AGENDA_CUMPLIMIENTO', 'Agendado para Reunión (Cumplimiento TSP)'), ('CUMPLIMIENTO_EMITIDO', 'Auto de Cumplimiento/Ejecutoria Emitido'), ('CUMPLIMIENTO_NOTIFICADO', 'Cumplimiento TSP Notificado (Pte. Archivo)'), ('CONCLUIDO_TSP_TPE', 'Archivado / Concluido (TSP-TPE)'), ('NULIDAD_TSP', 'Nulidad de Obrados por el TSP'), ('INSTITUCIONAL', 'Acto Institucional')], db_index=True, default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
        migrations.AlterField(
            model_name='historicalsim',
            name='tipo',
            field=models.CharField(choices=[('DISCIPLINARIO', 'DISCIPLINARIO'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('ASCENSO POSTUMO', 'ASCENSO POSTUMO'), ('SOLICITUD DE RETIRO VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MAXIMA'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD RESTITUCIÓN ANTIGUEDAD'), ('SOLICITUD_DE_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ASCENSO_AL_GRADO_INMEDIATO_SUPERIOR', 'SOLICITUD ASCENSO AL GRADO INMEDIATO SUPERIOR'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('INSTITUCIONAL', 'INSTITUCIONAL')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ARCHIVO_OBRADOS', 'ARCHIVO DE OBRADOS'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('SANCIONES_DISCIPLINARIAS', 'SANCIONES DISCIPLINARIAS'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'NO HA LUGAR A LA SANCIÓN DISCIPLINARIA'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO (EJECUTIVA)'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B (PÉRDIDA DE ANTIGÜEDAD)'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('SANCION_BAJA', 'SANCIÓN BAJA'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D (PERMISO MÉDICO)'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MÁXIMA'), ('SOLICITUD_ASCENSO', 'SOLICITUD DE ASCENSO'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD DE RESTITUCIÓN DE ANTIGÜEDAD'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('OTRO', 'OTRO'), ('PROCEDENCIA', 'PROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('IMPROCEDENCIA', 'IMPROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('POSESION', 'POSESIÓN DEL TPE'), ('CIERRE', 'CIERRE DEL TPE')], max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='estado',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('PROCESO_EN_EL_TSP', 'Proceso en el TSP'), ('CUMPLIMIENTO_EN_TPE', 'En Cumplimiento (Devuelto por TSP)'), ('PROCESO_CONCLUIDO_TPE', 'Proceso Concluido (TPE)'), ('PROCESO_CONCLUIDO_TSP_TPE', 'Proceso Concluido (TSP-TPE)'), ('PROCESO_EJECUTADO', 'Proceso Ejecutado'), ('OBSERVADO', 'Observado'), ('INSTITUCIONAL_VIGENTE', 'Vigente (Institucional)'), ('INSTITUCIONAL_CONCLUIDO', 'Concluido (Institucional)')], db_index=True, default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='fase',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'En Espera de RAP (plazo 3 días)'), ('EN_AGENDA_EJECUTORIA', 'En Agenda (Auto de Ejecutoria)'), ('EN_EJECUTORIA', 'Auto de Ejecutoria Emitido'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorándum Retornado (Proceso Ejecutado)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('RECIBIDO_TSP', 'Pronunciamiento TSP Recibido en TPE'), ('EN_CUMPLIMIENTO', 'Auto de Cumplimiento/Ejecutoria en Elaboración'), ('EN_AGENDA_CUMPLIMIENTO', 'Agendado para Reunión (Cumplimiento TSP)'), ('CUMPLIMIENTO_EMITIDO', 'Auto de Cumplimiento/Ejecutoria Emitido'), ('CUMPLIMIENTO_NOTIFICADO', 'Cumplimiento TSP Notificado (Pte. Archivo)'), ('CONCLUIDO_TSP_TPE', 'Archivado / Concluido (TSP-TPE)'), ('NULIDAD_TSP', 'Nulidad de Obrados por el TSP'), ('INSTITUCIONAL', 'Acto Institucional')], db_index=True, default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='tipo',
            field=models.CharField(choices=[('DISCIPLINARIO', 'DISCIPLINARIO'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('ASCENSO POSTUMO', 'ASCENSO POSTUMO'), ('SOLICITUD DE RETIRO VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MAXIMA'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD RESTITUCIÓN ANTIGUEDAD'), ('SOLICITUD_DE_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ASCENSO_AL_GRADO_INMEDIATO_SUPERIOR', 'SOLICITUD ASCENSO AL GRADO INMEDIATO SUPERIOR'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('INSTITUCIONAL', 'INSTITUCIONAL')], max_length=100, verbose_name='Tipo'),
        ),
    ]
