# Generated by Django 6.0.2 on 2026-04-19 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0016_custodiasim_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiasim',
            name='abog_destino',
            field=models.ForeignKey(blank=True, help_text='A quién Admin2 debe entregar la carpeta (ej: para ejecutoria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodias_destino', to='tpe_app.abog', verbose_name='Abogado Destino'),
        ),
        migrations.AlterField(
            model_name='custodiasim',
            name='motivo',
            field=models.CharField(blank=True, choices=[('AGENDA', 'Para agenda del tribunal'), ('REVISION', 'Revisión del abogado'), ('NOTIFICACION', 'Para notificación'), ('APELACION_TSP', 'Elevado al TSP'), ('EJECUTORIA', 'Para ejecutoria/cumplimiento'), ('ARCHIVO', 'Archivado / Concluido')], max_length=20, null=True, verbose_name='Motivo de la custodia'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('MASTER', 'Master (Control Total)'), ('ADMINISTRADOR', 'Administrador de Sistemas'), ('AYUDANTE', 'Ayudante (Registro Histórico)'), ('ADMIN1_AGENDADOR', 'Administrativo 1 (Agendador)'), ('ADMIN2_ARCHIVO', 'Administrativo 2 (Archivo SIM)'), ('ADMIN3_NOTIFICADOR', 'Administrativo 3 (Notificador)'), ('ABOG1_ASESOR', 'Abogado 1 (Asesor/1ra Resolución)'), ('ABOG2_AUTOS', 'Abogado 2 (Autos de Ejecución)'), ('ABOG3_BUSCADOR', 'Abogado 3 (Búsqueda de Antecedentes)'), ('VOCAL_TPE', 'Vocal TPE (Secretario de Actas)'), ('ASESOR_JURIDICO', 'Asesor Jurídico del DPTO-I'), ('ABOGADO', 'Abogado (General)'), ('BUSCADOR', 'Buscador (General)')], max_length=20, verbose_name='Rol/Perfil'),
        ),
    ]
