# Generated by Django 5.2 on 2026-05-11 14:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0017_abog_sim_agenda_alter_autotpe_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECUSA', 'AUTO DE RECUSA'), ('AUTO_ACLARATORIO', 'AUTO ACLARATORIO'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO'), ('AUTO_FACULTAD', 'AUTO DE FACULTAD'), ('AUTO_RESPUESTA', 'AUTO DE RESPUESTA')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='historicalautotpe',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'SOBRESEÍDO'), ('NULIDAD_OBRADOS', 'NULIDAD DE OBRADOS'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('AUTO_CUMPLIMIENTO', 'AUTO DE CUMPLIMIENTO'), ('AUTO_EJECUTORIA', 'AUTO DE EJECUTORIA'), ('AUTO_EXCUSA', 'AUTO DE EXCUSA'), ('AUTO_RECUSA', 'AUTO DE RECUSA'), ('AUTO_ACLARATORIO', 'AUTO ACLARATORIO'), ('AUTO_RECHAZO_RECURSO', 'AUTO DE RECHAZO DE RECURSO'), ('AUTO_FACULTAD', 'AUTO DE FACULTAD'), ('AUTO_RESPUESTA', 'AUTO DE RESPUESTA')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
        migrations.AlterField(
            model_name='votovocal',
            name='voto',
            field=models.CharField(choices=[('APRUEBA', 'Aprueba / Procedente'), ('RECHAZA', 'Rechaza / Improcedente'), ('ABSTIENE', 'Se abstiene'), ('AUSENTE', 'Ausente en sesión'), ('EXCUSADO', 'Excusado del caso')], max_length=15),
        ),
        migrations.CreateModel(
            name='DocumentoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCIDENTE', 'INCIDENTE'), ('RECURSO_FUERA_PLAZO', 'RECURSO FUERA DE PLAZO'), ('AMPARO_CONSTITUCIONAL', 'AMPARO CONSTITUCIONAL')], db_index=True, max_length=30, verbose_name='Tipo de Documento')),
                ('ntd', models.CharField(db_index=True, max_length=30, verbose_name='N° NTD')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso al TPE')),
                ('objeto', models.TextField(verbose_name='Objeto del Documento')),
                ('plazo_respuesta', models.DateField(blank=True, null=True, verbose_name='Plazo de Respuesta (si aplica)')),
                ('abogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_recurrente_asignados', to='tpe_app.pm', verbose_name='Abogado asignado')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recurrente_como_recurrente', to='tpe_app.pm', verbose_name='Recurrente')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recurrente', to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'Documento del Recurrente',
                'verbose_name_plural': 'Documentos del Recurrente',
                'db_table': 'documento_recurrente',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='autotpe',
            name='documento_recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_respuesta', to='tpe_app.documentorecurrente', verbose_name='Documento del Recurrente al que responde'),
        ),
        migrations.AddField(
            model_name='historicalautotpe',
            name='documento_recurrente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.documentorecurrente', verbose_name='Documento del Recurrente al que responde'),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentoRecurrente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCIDENTE', 'INCIDENTE'), ('RECURSO_FUERA_PLAZO', 'RECURSO FUERA DE PLAZO'), ('AMPARO_CONSTITUCIONAL', 'AMPARO CONSTITUCIONAL')], db_index=True, max_length=30, verbose_name='Tipo de Documento')),
                ('ntd', models.CharField(db_index=True, max_length=30, verbose_name='N° NTD')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso al TPE')),
                ('objeto', models.TextField(verbose_name='Objeto del Documento')),
                ('plazo_respuesta', models.DateField(blank=True, null=True, verbose_name='Plazo de Respuesta (si aplica)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('abogado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.pm', verbose_name='Abogado asignado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.pm', verbose_name='Recurrente')),
                ('sim', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'historical Documento del Recurrente',
                'verbose_name_plural': 'historical Documentos del Recurrente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='documentorecurrente',
            index=models.Index(fields=['sim'], name='documento_r_sim_id_d68a12_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorecurrente',
            index=models.Index(fields=['pm'], name='documento_r_pm_id_3ee0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorecurrente',
            index=models.Index(fields=['tipo'], name='documento_r_tipo_de7735_idx'),
        ),
    ]
