# Generated by Django 6.0.2 on 2026-04-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0017_custodiasim_abog_destino_alter_custodiasim_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodiasim',
            name='estado',
            field=models.CharField(choices=[('RECIBIDA_CONFORME', 'Recibida Conforme'), ('PENDIENTE_CONFIRMACION', 'Pendiente de Confirmación')], default='ACTIVA', max_length=25, verbose_name='Estado de la Custodia'),
        ),
    ]
