# Generated by Django 5.2.12 on 2026-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0017_remove_res_res_resum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='RES_FECAGEN',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_Agenda'),
        ),
    ]
