# Generated by Django 6.0.2 on 2026-04-21 22:17

from django.db import migrations


def update_custodio_states(apps, schema_editor):
    """Actualizar ACTIVA a RECIBIDA_CONFORME"""
    CustodiaSIM = apps.get_model('tpe_app', 'CustodiaSIM')
    CustodiaSIM.objects.filter(estado='ACTIVA').update(estado='RECIBIDA_CONFORME')


def reverse_update(apps, schema_editor):
    """Revertir RECIBIDA_CONFORME a ACTIVA"""
    CustodiaSIM = apps.get_model('tpe_app', 'CustodiaSIM')
    CustodiaSIM.objects.filter(estado='RECIBIDA_CONFORME').update(estado='ACTIVA')


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0018_alter_custodiasim_estado'),
    ]

    operations = [
        migrations.RunPython(update_custodio_states, reverse_update),
    ]
