# Generated by Django 5.2.12 on 2026-03-25 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0018_alter_res_res_fecagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res',
            name='RES_AGENDA',
        ),
        migrations.RemoveField(
            model_name='res',
            name='RES_FECAGEN',
        ),
        migrations.CreateModel(
            name='AGENDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AG_NUM', models.CharField(help_text='Ej: 15/26', max_length=20, verbose_name='Número de Reunión')),
                ('AG_NUMDICT', models.CharField(blank=True, help_text='Ej: 02/26', max_length=10, null=True, verbose_name='N° Dictamen')),
                ('AG_FEC', models.DateField(verbose_name='Fecha de la Reunión')),
                ('AG_RESULTADO', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESOLUCION', 'Resolución'), ('AUTO_TPE', 'Auto TPE')], default='PENDIENTE', max_length=20, verbose_name='Resultado')),
                ('ID_ABOG', models.ForeignKey(blank=True, db_column='ID_ABOG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado')),
                ('ID_SIM', models.ForeignKey(db_column='ID_SIM', on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'agenda',
                'ordering': ['-AG_FEC'],
            },
        ),
        migrations.AddField(
            model_name='autotpe',
            name='ID_AGENDA',
            field=models.ForeignKey(blank=True, db_column='ID_AGENDA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda'),
        ),
        migrations.AddField(
            model_name='res',
            name='ID_AGENDA',
            field=models.ForeignKey(blank=True, db_column='ID_AGENDA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda'),
        ),
    ]
