# Generated by Django 6.0.2 on 2026-04-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0019_update_custodio_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiasim',
            name='fecha_oficio_archivo',
            field=models.DateField(blank=True, help_text='Fecha de envío a ARCHIVO PERMANENTE', null=True, verbose_name='Fecha del Oficio (ARCHIVO/SPRODA)'),
        ),
        migrations.AddField(
            model_name='custodiasim',
            name='nro_oficio_archivo',
            field=models.CharField(blank=True, help_text='Ej: OF-001/26 — cuando se envía a archivo permanente', max_length=30, null=True, verbose_name='Número de Oficio (ARCHIVO/SPRODA)'),
        ),
        migrations.AlterField(
            model_name='custodiasim',
            name='estado',
            field=models.CharField(choices=[('RECIBIDA_CONFORME', 'Recibida Conforme'), ('PENDIENTE_CONFIRMACION', 'Pendiente de Confirmación')], default='RECIBIDA_CONFORME', max_length=25, verbose_name='Estado de la Custodia'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_ESTADO',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('PROCESO_EN_EL_TSP', 'Proceso en el TSP'), ('PROCESO_CONCLUIDO_TPE', 'Proceso Concluido (TPE)'), ('PROCESO_EJECUTADO', 'Proceso Ejecutado'), ('OBSERVADO', 'Observado')], default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
    ]
