# Generated by Django 5.2 on 2026-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0019_alter_historicalresolucion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpm',
            name='arma',
            field=models.CharField(blank=True, choices=[('INF.', 'INF.'), ('CAB.', 'CAB.'), ('ART.', 'ART.'), ('ING.', 'ING.'), ('COM.', 'COM.'), ('LOG.', 'LOG.'), ('M.B.', 'M.B.'), ('INT.', 'INT.'), ('SAN.', 'SAN.'), ('MOT.', 'MOT.'), ('TGRAFO.', 'TGRAFO.'), ('AV.', 'AV.'), ('MÚS.', 'MÚS.')], max_length=20, null=True, verbose_name='Arma'),
        ),
        migrations.AlterField(
            model_name='historicalresolucion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ARCHIVO_OBRADOS', 'ARCHIVO DE OBRADOS'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('SANCIONES_DISCIPLINARIAS', 'SANCIONES DISCIPLINARIAS'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'NO HA LUGAR A LA SANCIÓN DISCIPLINARIA'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO (EJECUTIVA)'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('PERDIDA_DE_ANTIGUEDAD', 'PÉRDIDA DE ANTIGÜEDAD'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('SANCION_BAJA', 'SANCIÓN BAJA'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D (PERMISO MÉDICO)'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MÁXIMA'), ('SOLICITUD_ASCENSO', 'SOLICITUD DE ASCENSO'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD DE RESTITUCIÓN DE ANTIGÜEDAD'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('OTRO', 'OTRO'), ('PROCEDENCIA', 'PROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('PROCEDENCIA_EN_PARTE', 'PROCEDENCIA EN PARTE'), ('IMPROCEDENCIA', 'IMPROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('POSESION', 'POSESIÓN DEL TPE'), ('CIERRE', 'CIERRE DEL TPE')], max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pm',
            name='arma',
            field=models.CharField(blank=True, choices=[('INF.', 'INF.'), ('CAB.', 'CAB.'), ('ART.', 'ART.'), ('ING.', 'ING.'), ('COM.', 'COM.'), ('LOG.', 'LOG.'), ('M.B.', 'M.B.'), ('INT.', 'INT.'), ('SAN.', 'SAN.'), ('MOT.', 'MOT.'), ('TGRAFO.', 'TGRAFO.'), ('AV.', 'AV.'), ('MÚS.', 'MÚS.')], max_length=20, null=True, verbose_name='Arma'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ARCHIVO_OBRADOS', 'ARCHIVO DE OBRADOS'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('SANCIONES_DISCIPLINARIAS', 'SANCIONES DISCIPLINARIAS'), ('NO_HA_LUGAR_SANCION_DISCIPLINARIA', 'NO HA LUGAR A LA SANCIÓN DISCIPLINARIA'), ('SOLICITUD_DE_RETIRO_VOLUNTARIO', 'SOLICITUD DE RETIRO VOLUNTARIO'), ('SANCION_ARRESTO', 'SANCIÓN ARRESTO (EJECUTIVA)'), ('SANCION_LETRA_B', 'SANCIÓN LETRA B'), ('PERDIDA_DE_ANTIGUEDAD', 'PÉRDIDA DE ANTIGÜEDAD'), ('SANCION_RETIRO_OBLIGATORIO', 'SANCIÓN RETIRO OBLIGATORIO'), ('SANCION_BAJA', 'SANCIÓN BAJA'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D (PERMISO MÉDICO)'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MÁXIMA'), ('SOLICITUD_ASCENSO', 'SOLICITUD DE ASCENSO'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD DE RESTITUCIÓN DE ANTIGÜEDAD'), ('SOLICITUD_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)'), ('OTRO', 'OTRO'), ('PROCEDENCIA', 'PROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('PROCEDENCIA_EN_PARTE', 'PROCEDENCIA EN PARTE'), ('IMPROCEDENCIA', 'IMPROCEDENCIA A SU RECURSO DE RECONSIDERACIÓN'), ('POSESION', 'POSESIÓN DEL TPE'), ('CIERRE', 'CIERRE DEL TPE')], max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
