# Generated by Django 6.0.3 on 2026-03-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0019_remove_res_res_agenda_remove_res_res_fecagen_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='SIM_ESTADO',
            field=models.CharField(choices=[('PARA_AGENDA', 'Para Agenda'), ('PROCESO_EN_EL_TPE', 'Proceso en el TPE'), ('EN_APELACION_TSP', 'En Apelación TSP'), ('CONCLUIDO', 'Concluido'), ('OBSERVADO', 'Observado')], default='PARA_AGENDA', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_TIPO',
            field=models.CharField(choices=[('DISCIPLINARIO', 'DISCIPLINARIO'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('ASCENSO POSTUMO', 'ASCENSO POSTUMO'), ('SOLICITUD_LETRA_D', 'SOLICITUD LETRA D'), ('SOLICITUD_LICENCIA_MAXIMA', 'SOLICITUD LICENCIA MAXIMA'), ('SOLICITUD_RESTITUCION_ANTIGUEDAD', 'SOLICITUD RESTITUCIÓN ANTIGUEDAD'), ('SOLICITUD_DE_RESTITUCION_DE_DERECHOS_PROFESIONALES', 'SOLICITUD DE RESTITUCIÓN DE DERECHOS PROFESIONALES'), ('SOLICITUD_ASCENSO_AL_GRADO_INMEDIATO_SUPERIOR', 'SOLICITUD ASCENSO AL GRADO INMEDIATO SUPERIOR'), ('SOLICITUD_ART_114_(Invalidez Instructor)', 'SOLICITUD ARTÍCULO 114 (INVALIDEZ INSTRUCTOR)'), ('SOLICITUD_ART_117_(Fallecimiento)', 'SOLICITUD ARTÍCULO 117 (FALLECIMIENTO)'), ('SOLICITUD_ART_118_(Invalidez Sldo)', 'SOLICITUD ARTÍCULO 118 (INVALIDEZ SLDO)')], max_length=100, verbose_name='Tipo'),
        ),
    ]
