# Generated by Django 5.2 on 2026-05-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0020_alter_historicalpm_arma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsim',
            name='fase',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'EN ESPERA DE SU REC. AP. (15 DIAS)'), ('EN_AGENDA_EJECUTORIA', 'Agendado para Ejecutoria'), ('EN_EJECUTORIA', 'Sesión de Ejecutoria Realizada'), ('EJECUTORIA_PARA_NOTIFICAR', 'Auto de Ejecutoria Emitido (Pte. Notificar)'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorándum Retornado (Proceso Ejecutado)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('RECIBIDO_TSP', 'Pronunciamiento TSP Recibido en TPE'), ('EN_CUMPLIMIENTO', 'Auto de Cumplimiento/Ejecutoria en Elaboración'), ('EN_AGENDA_CUMPLIMIENTO', 'Agendado para Reunión (Cumplimiento TSP)'), ('CUMPLIMIENTO_EMITIDO', 'Auto de Cumplimiento/Ejecutoria Emitido'), ('CUMPLIMIENTO_NOTIFICADO', 'Cumplimiento TSP Notificado (Pte. Archivo)'), ('CONCLUIDO_TSP_TPE', 'Archivado / Concluido (TSP-TPE)'), ('NULIDAD_TSP', 'Nulidad de Obrados por el TSP'), ('INSTITUCIONAL', 'Acto Institucional')], db_index=True, default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='fase',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'EN ESPERA DE SU REC. AP. (15 DIAS)'), ('EN_AGENDA_EJECUTORIA', 'Agendado para Ejecutoria'), ('EN_EJECUTORIA', 'Sesión de Ejecutoria Realizada'), ('EJECUTORIA_PARA_NOTIFICAR', 'Auto de Ejecutoria Emitido (Pte. Notificar)'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorándum Retornado (Proceso Ejecutado)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('RECIBIDO_TSP', 'Pronunciamiento TSP Recibido en TPE'), ('EN_CUMPLIMIENTO', 'Auto de Cumplimiento/Ejecutoria en Elaboración'), ('EN_AGENDA_CUMPLIMIENTO', 'Agendado para Reunión (Cumplimiento TSP)'), ('CUMPLIMIENTO_EMITIDO', 'Auto de Cumplimiento/Ejecutoria Emitido'), ('CUMPLIMIENTO_NOTIFICADO', 'Cumplimiento TSP Notificado (Pte. Archivo)'), ('CONCLUIDO_TSP_TPE', 'Archivado / Concluido (TSP-TPE)'), ('NULIDAD_TSP', 'Nulidad de Obrados por el TSP'), ('INSTITUCIONAL', 'Acto Institucional')], db_index=True, default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
    ]
