# Generated by Django 6.0.3 on 2026-03-27 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0020_alter_sim_sim_estado_alter_sim_sim_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='AG_NUMDICT',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='AG_RESULTADO',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='ID_ABOG',
        ),
        migrations.RemoveField(
            model_name='rr',
            name='RR_AGENDA',
        ),
        migrations.RemoveField(
            model_name='rr',
            name='RR_FECAGEN',
        ),
        migrations.AddField(
            model_name='rr',
            name='ID_AGENDA',
            field=models.ForeignKey(blank=True, db_column='ID_AGENDA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda'),
        ),
    ]
