# Generated by Django 6.0.2 on 2026-04-21 22:41

from django.db import migrations


def update_sim_states(apps, schema_editor):
    """Actualizar estados del SIM"""
    SIM = apps.get_model('tpe_app', 'SIM')
    SIM.objects.filter(SIM_ESTADO='EN_APELACION_TSP').update(SIM_ESTADO='PROCESO_EN_EL_TSP')
    SIM.objects.filter(SIM_ESTADO='CONCLUIDO').update(SIM_ESTADO='PROCESO_CONCLUIDO_TPE')


def reverse_update(apps, schema_editor):
    """Revertir cambios"""
    SIM = apps.get_model('tpe_app', 'SIM')
    SIM.objects.filter(SIM_ESTADO='PROCESO_EN_EL_TSP').update(SIM_ESTADO='EN_APELACION_TSP')
    SIM.objects.filter(SIM_ESTADO='PROCESO_CONCLUIDO_TPE').update(SIM_ESTADO='CONCLUIDO')


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0020_custodiasim_fecha_oficio_archivo_and_more'),
    ]

    operations = [
        migrations.RunPython(update_sim_states, reverse_update),
    ]
