# Generated by Django 6.0.3 on 2026-03-27 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0021_remove_agenda_ag_numdict_remove_agenda_ag_resultado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOG_SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AB_ROL', models.CharField(choices=[('FISCAL', 'Fiscal'), ('DEFENSOR', 'Defensor'), ('ASESOR', 'Asesor'), ('OTRO', 'Otro')], max_length=20, verbose_name='Rol')),
                ('AB_FEC_ASIGNACION', models.DateField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('ID_ABOG', models.ForeignKey(db_column='ID_ABOG', on_delete=django.db.models.deletion.RESTRICT, to='tpe_app.abog', verbose_name='Abogado')),
                ('ID_SIM', models.ForeignKey(db_column='ID_SIM', on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario')),
            ],
            options={
                'verbose_name': 'Abogado en Sumario',
                'verbose_name_plural': 'Abogados en Sumario',
                'db_table': 'abog_sim',
                'unique_together': {('ID_SIM', 'ID_ABOG', 'AB_ROL')},
            },
        ),
        migrations.AddField(
            model_name='sim',
            name='abogados',
            field=models.ManyToManyField(through='tpe_app.ABOG_SIM', to='tpe_app.abog', verbose_name='Abogados asignados'),
        ),
    ]
