# Generated by Django 6.0.2 on 2026-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0021_update_sim_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='SIM_COD',
            field=models.CharField(help_text='Formato: PREFIJO-NUM/AÑO (ej: DJE-95/25, SASJUR-25/25, SDISCAPE-86/25)', max_length=25, unique=True, verbose_name='Código SIM'),
        ),
    ]
