# Generated by Django 5.2 on 2026-05-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0021_add_ejecutoria_para_notificar_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiasim',
            name='archivo_oficio',
            field=models.FileField(blank=True, null=True, upload_to='oficios_custodia/%Y/', verbose_name='PDF del Oficio'),
        ),
        migrations.AlterField(
            model_name='custodiasim',
            name='motivo',
            field=models.CharField(blank=True, choices=[('AGENDA', 'Para agenda del tribunal'), ('REVISION', 'Revisión del abogado'), ('NOTIFICACION', 'Para notificación'), ('APELACION_TSP', 'Elevado al TSP'), ('EJECUTORIA', 'Para ejecutoria/cumplimiento'), ('RESPUESTA_MEMORIAL', 'Respuesta a Memorial'), ('ARCHIVO', 'Archivado / Concluido')], max_length=20, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='custodiasim',
            name='tipo_custodio',
            field=models.CharField(choices=[('ADMIN2_ARCHIVO', 'Archivo del Tribunal'), ('ABOG_ASESOR', 'Abogado Asesor'), ('ABOG_RR', 'Abogado (Reconsideración)'), ('ABOG_AUTOS', 'Abogado (Autos)'), ('VOCAL_SESION', 'Secretario de Actas'), ('ADMIN1_AGENDADOR', 'Agendador'), ('ADMIN3_NOTIFICADOR', 'Notificador'), ('TSP', 'Tribunal Superior de Personal'), ('ARCHIVO', 'Archivo Permanente')], max_length=20, verbose_name='Tipo de Custodio'),
        ),
    ]
