# Generated by Django 6.0.2 on 2026-04-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0022_alter_sim_sim_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='SIM_MOTIVO_REAPERTURA',
            field=models.CharField(blank=True, choices=[('NULIDAD_OBRADOS', 'Nulidad de Obrados'), ('VICIO_PROCESAL', 'Vicio Procesal'), ('ERROR_JURIDICO', 'Error Jurídico'), ('FALTA_NOTIFICACION', 'Falta de Notificación'), ('OTRO', 'Otro Motivo')], help_text='¿Por qué se reabrió este sumario?', max_length=30, null=True, verbose_name='Motivo de Reapertura'),
        ),
        migrations.AddField(
            model_name='sim',
            name='SIM_ORIGEN',
            field=models.ForeignKey(blank=True, help_text='Si este SIM es reapertura de otro, referencia el original aquí', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reaperturas', to='tpe_app.sim', verbose_name='SIM Original'),
        ),
        migrations.AddField(
            model_name='sim',
            name='SIM_VERSION',
            field=models.IntegerField(default=1, help_text='1=original, 2=1ª reapertura, 3=2ª reapertura, etc.', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_COD',
            field=models.CharField(db_index=True, help_text='Formato: PREFIJO-NUM/AÑO (ej: DJE-95/25, SASJUR-25/25, SDISCAPE-86/25)', max_length=25, verbose_name='Código SIM'),
        ),
        migrations.AlterUniqueTogether(
            name='sim',
            unique_together={('SIM_COD', 'SIM_VERSION')},
        ),
    ]
