# Generated by Django 6.0.3 on 2026-03-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0022_abog_sim_sim_abogados'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abog_sim',
            unique_together={('ID_SIM', 'ID_ABOG')},
        ),
        migrations.RemoveField(
            model_name='abog_sim',
            name='AB_FEC_ASIGNACION',
        ),
        migrations.RemoveField(
            model_name='abog_sim',
            name='AB_ROL',
        ),
    ]
