# Generated by Django 5.2 on 2026-05-17 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0022_add_archivo_oficio_custodia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadjunto',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SHA-256 del archivo'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='tamano_bytes',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Tamano en bytes'),
        ),
    ]
