# Generated by Django 5.2.12 on 2026-03-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0023_alter_abog_sim_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-AG_FECPROG'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='AG_FEC',
        ),
        migrations.AddField(
            model_name='agenda',
            name='AG_FECPROG',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programada'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='AG_FECREAL',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Realizada'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='AG_NUM',
            field=models.CharField(help_text='Ej: VIGESIMA PRIMERA AGENDA', max_length=20, verbose_name='Número de Reunión'),
        ),
    ]
