# Generated by Django 5.2.12 on 2026-04-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0023_sim_sim_motivo_reapertura_sim_sim_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodiasim',
            name='tipo_custodio',
            field=models.CharField(choices=[('ADMIN2_ARCHIVO', 'Archivo del Tribunal'), ('ABOG_ASESOR', 'Abogado Asesor'), ('ABOG_RR', 'Abogado (Reconsideración)'), ('ABOG_AUTOS', 'Abogado (Autos)'), ('VOCAL_SESION', 'Secretario de Actas'), ('ADMIN1_AGENDADOR', 'Agendador'), ('ADMIN3_NOTIFICADOR', 'Notificador'), ('TSP', 'Tribunal Supremo Policial'), ('ARCHIVO', 'Archivo Permanente')], max_length=20, verbose_name='Tipo de Custodio'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_FASE',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'En Espera de RAP (plazo 3 días)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('EN_AGENDA_EJECUTORIA', 'En Agenda (Auto de Ejecutoria)'), ('EN_EJECUTORIA', 'Auto de Ejecutoria Emitido'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorandum Retornado (Proceso Ejecutado)')], default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
    ]
