# Generated by Django 5.2 on 2026-05-17 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0023_add_sha256_to_documentoadjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('VIEW_SIM', 'Consulta detalle SIM'), ('VIEW_PM', 'Consulta personal militar'), ('VIEW_HISTORIAL', 'Consulta historial personal'), ('EXPORT_PDF', 'Exportacion PDF'), ('EXPORT_EXCEL', 'Exportacion Excel'), ('EXPORT_BATCH', 'Exportacion por lotes'), ('DOWNLOAD_MEDIA', 'Descarga archivo media'), ('SEARCH', 'Busqueda'), ('LOGIN_OK', 'Login exitoso'), ('LOGIN_FAIL', 'Login fallido'), ('PASSWORD_CHANGE', 'Cambio de contrasena'), ('USER_CREATE', 'Creacion de usuario'), ('USER_ROLE_CHANGE', 'Cambio de rol'), ('PERMISSION_DENIED', 'Acceso denegado por rol')], db_index=True, max_length=30, verbose_name='Accion')),
                ('objeto_tipo', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Tipo de objeto')),
                ('objeto_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID del objeto')),
                ('detalle', models.CharField(blank=True, default='', max_length=200, verbose_name='Detalle')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=200, verbose_name='User-Agent')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos_log', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso (bitacora)',
                'verbose_name_plural': 'Bitacora de accesos',
                'db_table': 'acceso_log',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='acceso_log_usuario_912e3f_idx'), models.Index(fields=['accion', '-fecha'], name='acceso_log_accion_15416e_idx'), models.Index(fields=['objeto_tipo', 'objeto_id'], name='acceso_log_objeto__344737_idx')],
            },
        ),
    ]
