# Generated by Django 5.2 on 2026-05-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0024_add_acceso_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiasim',
            name='destino_final',
            field=models.CharField(blank=True, choices=[('SPRODA', 'SPRODA (Servicio de Personal y Recursos)'), ('DGJURE', 'DGJURE (Dirección General Jurídica del Ejército)'), ('SDISCAPE', 'SDISCAPE (Servicio de Información, Documentación y Censo)'), ('SCADE', 'SCADE (Sistema de Capacitación y Desarrollo)'), ('ASCENSO', 'ASCENSO (Sección de Ascensos)'), ('OTRO', 'Otro destino')], max_length=30, null=True, verbose_name='Destino Final de la Carpeta'),
        ),
    ]
