# Generated by Django 5.2.12 on 2026-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0024_alter_agenda_options_remove_agenda_ag_fec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='AG_TIPO',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Reunión'),
        ),
    ]
