# Generated by Django 5.2 on 2026-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0024_alter_custodiasim_tipo_custodio_alter_sim_sim_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_MEMO_NUM',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='N° Memorándum'),
        ),
    ]
