# Generated by Django 5.2.12 on 2026-03-27 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0025_agenda_ag_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DICTAMEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DIC_NUM', models.CharField(help_text='Ej: VIGESIMA PRIMERA AGENDA', max_length=20, verbose_name='Número de Reunión')),
                ('DIC_CONCL', models.DateField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('ID_ABOG', models.ForeignKey(blank=True, db_column='ID_ABOG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado')),
                ('ID_AGENDA', models.ForeignKey(db_column='ID_AGENDA', on_delete=django.db.models.deletion.CASCADE, to='tpe_app.agenda', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Dictamen',
                'verbose_name_plural': 'Dictámenes',
                'db_table': 'dictamen',
                'ordering': ['-ID_AGENDA__AG_FECPROG'],
            },
        ),
    ]
