# Generated by Django 5.2 on 2026-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0025_custodiasim_destino_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodiasim',
            name='destino_final',
            field=models.CharField(blank=True, choices=[('SPRODA', 'SPRODA (Sección de Procesamiento de Datos)'), ('DGJURE', 'DGJURE (Dirección General Jurídica del Ejército)'), ('SDISCAPE', 'SDISCAPE (Sección de Disciplina y Capacitación)'), ('SCADE', 'SCADE (Sección de Cargos y Destinos)'), ('SASCENSO', 'SASCENSO (Sección Ascenso)'), ('OTRO', 'Otro destino')], max_length=30, null=True, verbose_name='Destino Final de la Carpeta'),
        ),
    ]
