# Generated by Django 6.0.2 on 2026-04-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0025_alter_autotpe_tpe_memo_num_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamen',
            name='resultado_tribunal',
            field=models.CharField(blank=True, choices=[('PROCEDENTE', 'Procedente'), ('IMPROCEDENTE', 'Improcedente'), ('MIXTO', 'Votos divididos')], max_length=15, null=True, verbose_name='Resultado del tribunal'),
        ),
        migrations.AlterField(
            model_name='custodiasim',
            name='tipo_custodio',
            field=models.CharField(choices=[('ADMIN2_ARCHIVO', 'Archivo del Tribunal'), ('ABOG_ASESOR', 'Abogado Asesor'), ('ABOG_RR', 'Abogado (Reconsideración)'), ('ABOG_AUTOS', 'Abogado (Autos)'), ('VOCAL_SESION', 'Secretario de Actas'), ('ADMIN1_AGENDADOR', 'Agendador'), ('ADMIN3_NOTIFICADOR', 'Notificador'), ('TSP', 'Tribunal Supremo Policial'), ('ARCHIVO', 'Archivo Permanente')], max_length=20, verbose_name='Tipo de Custodio'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='SIM_FASE',
            field=models.CharField(blank=True, choices=[('PARA_AGENDA', 'Para Agenda'), ('EN_DICTAMEN_1RA', 'En Dictamen (1ra. Resolución)'), ('1RA_RESOLUCION', 'Emitida 1ra. Resolución'), ('NOTIFICACION_1RA', 'En Proceso de Notificación (1ra.)'), ('NOTIFICADO_1RA', 'Notificado (1ra. Resolución)'), ('EN_ESPERA_RR', 'En Espera de RR (plazo 15 días)'), ('PARA_AGENDA_RR', 'Para Agenda (RR)'), ('EN_DICTAMEN_RR', 'En Dictamen (2da. Resolución / RR)'), ('2DA_RESOLUCION', 'Emitida 2da. Resolución (RR)'), ('NOTIFICACION_RR', 'En Proceso de Notificación (RR)'), ('NOTIFICADO_RR', 'Notificado (RR)'), ('EN_ESPERA_RAP', 'En Espera de RAP (plazo 3 días)'), ('ELEVADO_TSP', 'Elevado al TSP'), ('EN_AGENDA_EJECUTORIA', 'En Agenda (Auto de Ejecutoria)'), ('EN_EJECUTORIA', 'Auto de Ejecutoria Emitido'), ('EJECUTORIA_NOTIFICADA', 'Ejecutoria Notificada (Pte. Archivo)'), ('PENDIENTE_ARCHIVO', 'Pendiente Archivo SPRODA'), ('CONCLUIDO', 'Archivado / Concluido (TPE)'), ('MEMORANDUM_RETORNADO', 'Memorandum Retornado (Proceso Ejecutado)')], default='PARA_AGENDA', max_length=30, null=True, verbose_name='Fase detallada del flujo'),
        ),
        migrations.CreateModel(
            name='AsistenciaVocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('EXCUSADO', 'Excusado')], default='PRESENTE', max_length=10)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tpe_app.agenda')),
                ('vocal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='tpe_app.vocal_tpe')),
            ],
            options={
                'verbose_name': 'Asistencia a Sesión',
                'verbose_name_plural': 'Asistencias a Sesiones',
                'db_table': 'asistencia_vocal',
                'ordering': ['vocal__cargo', 'vocal__pm__PM_PATERNO'],
                'unique_together': {('agenda', 'vocal')},
            },
        ),
        migrations.CreateModel(
            name='VotoVocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('APRUEBA', 'Aprueba / Procedente'), ('RECHAZA', 'Rechaza / Improcedente'), ('ABSTIENE', 'Se abstiene'), ('AUSENTE', 'Ausente en sesión')], max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('dictamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='tpe_app.dictamen')),
                ('vocal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos_emitidos', to='tpe_app.vocal_tpe')),
            ],
            options={
                'verbose_name': 'Voto del Vocal',
                'verbose_name_plural': 'Votos de Vocales',
                'db_table': 'voto_vocal',
                'ordering': ['vocal__cargo', 'vocal__pm__PM_PATERNO'],
                'unique_together': {('dictamen', 'vocal')},
            },
        ),
    ]
