# Generated by Django 6.0.3 on 2026-03-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0026_dictamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamen',
            name='DIC_CONCL',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dictamen Sugerido'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='DIC_NUM',
            field=models.CharField(help_text='Ej: 25/2026', max_length=20, verbose_name='Número de Dictamen'),
        ),
    ]
