# Generated by Django 6.0.3 on 2026-03-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0027_alter_dictamen_dic_concl_alter_dictamen_dic_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rr',
            name='RR_FEC',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='rr',
            name='RR_NUM',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='rr',
            name='RR_RESOL',
            field=models.TextField(blank=True, null=True, verbose_name='Resolución'),
        ),
    ]
