# Generated by Django 5.2 on 2026-09-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0027_alter_historicalresolucion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resolucion',
            unique_together={('numero', 'instancia', 'pm')},
        ),
    ]
