# Generated by Django 6.0.3 on 2026-03-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0028_alter_rr_rr_fec_alter_rr_rr_num_alter_rr_rr_resol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rap',
            name='RAP_FECPRESEN',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación del Recurso de Apelación al TSP'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_FEC',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Auto'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_NUM',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Auto'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_RESOL',
            field=models.TextField(blank=True, null=True, verbose_name='Resolución'),
        ),
        migrations.AlterField(
            model_name='autotpe',
            name='TPE_TIPO',
            field=models.CharField(blank=True, choices=[('SOBRESEIDO', 'Sobreseído'), ('NULIDAD_OBRADOS', 'Nulidad de Obrados'), ('SANCION_ARRESTO', 'Sanción Arresto'), ('SANCION_LETRA_B', 'Sanción Letra B'), ('SANCION_RETIRO_OBLIGATORIO', 'Sanción Retiro Obligatorio'), ('AUTO_CUMPLIMIENTO', 'Auto de Cumplimiento'), ('AUTO_EJECUTORIA', 'Auto de Ejecutoria'), ('AUTO_EXCUSA', 'Auto de Excusa'), ('AUTO_RECHAZO_RECURSO', 'Auto de Rechazo de Recurso')], max_length=100, null=True, verbose_name='Tipo de Auto'),
        ),
    ]
