# Generated by Django 6.0.3 on 2026-03-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0029_rap_rap_fecpresen_alter_autotpe_tpe_fec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rap',
            name='RAP_RESUM',
        ),
        migrations.AddField(
            model_name='rap',
            name='RAP_TIPO',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de Resolución TSP'),
        ),
    ]
