# Generated by Django 6.0.3 on 2026-03-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0030_remove_rap_rap_resum_rap_rap_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotsp',
            name='TSP_EJECU_FECNOT',
        ),
        migrations.RemoveField(
            model_name='autotsp',
            name='TSP_EJECU_NOT',
        ),
        migrations.AlterField(
            model_name='rap',
            name='RAP_TIPO',
            field=models.TextField(blank=True, choices=[('REVOCAR', 'REVOCAR'), ('CONFIRMAR', 'CONFIRMAR'), ('MODIFICAR', 'MODIFICAR'), ('ANULAR HASTA EL VICIO MAS ANTIGUO', 'ANULAR HASTA EL VICIO MAS ANTIGUO'), ('OTRO', 'OTRO')], null=True, verbose_name='Tipo de Resolución TSP'),
        ),
    ]
