# Generated by Django 6.0.3 on 2026-03-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0031_remove_autotsp_tsp_ejecu_fecnot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raee',
            name='RAE_AGENDA',
        ),
        migrations.RemoveField(
            model_name='raee',
            name='RAE_FECAGEN',
        ),
        migrations.RemoveField(
            model_name='raee',
            name='RAE_FECOFI',
        ),
        migrations.RemoveField(
            model_name='raee',
            name='RAE_OFI',
        ),
        migrations.AlterField(
            model_name='rap',
            name='RAP_TIPO',
            field=models.CharField(blank=True, choices=[('REVOCAR', 'REVOCAR'), ('CONFIRMAR', 'CONFIRMAR'), ('MODIFICAR', 'MODIFICAR'), ('ANULAR HASTA EL VICIO MAS ANTIGUO', 'ANULAR HASTA EL VICIO MAS ANTIGUO'), ('OTRO', 'OTRO')], max_length=50, null=True, verbose_name='Tipo de Resolución TSP'),
        ),
    ]
