# Generated by Django 6.0.3 on 2026-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0032_remove_raee_rae_agenda_remove_raee_rae_fecagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictamen',
            options={'verbose_name': 'Dictamen', 'verbose_name_plural': 'Dictámenes'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='AG_FECPROG',
            field=models.DateField(blank=True, db_column='AG_FECPROG', null=True, verbose_name='Fecha Programada'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='AG_FECREAL',
            field=models.DateField(blank=True, db_column='AG_FECREAL', null=True, verbose_name='Fecha Realizada'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='AG_NUM',
            field=models.CharField(db_column='AG_NUM', max_length=50, unique=True, verbose_name='Número de Agenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='AG_TIPO',
            field=models.CharField(blank=True, choices=[('ORDINARIA', 'Sesión Ordinaria'), ('EXTRAORDINARIA', 'Sesión Extraordinaria')], db_column='AG_TIPO', max_length=50, null=True, verbose_name='Tipo de Agenda'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='DIC_CONCL',
            field=models.CharField(blank=True, db_column='DIC_CONCL', max_length=255, null=True, verbose_name='Conclusión'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='DIC_NUM',
            field=models.CharField(db_column='DIC_NUM', max_length=20, verbose_name='Número de Dictamen'),
        ),
    ]
