# Generated by Django 6.0.3 on 2026-03-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0033_alter_dictamen_options_alter_agenda_ag_fecprog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='AG_FECPROG',
            field=models.DateField(blank=True, db_column='AG_FECPROG', null=True, verbose_name='Fecha Programada'),
        ),
    ]
