# Generated by Django 6.0.3 on 2026-04-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0035_remove_abog_id_remove_pm_id_abog_ab_id_pm_pm_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictamen',
            options={'ordering': ['-ID_AGENDA'], 'verbose_name': 'Dictamen', 'verbose_name_plural': 'Dictámenes'},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='ID_SIM',
        ),
        migrations.AddField(
            model_name='dictamen',
            name='ID_SIM',
            field=models.ForeignKey(db_column='ID_SIM', default=1, on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='res',
            name='ID_DICTAMEN',
            field=models.ForeignKey(blank=True, db_column='ID_DICTAMEN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.dictamen', verbose_name='Dictamen origen'),
        ),
        migrations.AlterField(
            model_name='autotsp',
            name='ID_SIM',
            field=models.ForeignKey(blank=True, db_column='ID_SIM', null=True, on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='DIC_CONCL',
            field=models.CharField(blank=True, db_column='DIC_CONCL', max_length=255, null=True, verbose_name='Conclusión / Recomendación'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='DIC_NUM',
            field=models.CharField(blank=True, db_column='DIC_NUM', max_length=20, null=True, verbose_name='Número de Dictamen'),
        ),
    ]
