# Generated by Django 4.2 on 2026-04-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0037_standardize_schema'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='dictamen',
                    options={'ordering': ['-agenda'], 'verbose_name': 'Dictamen', 'verbose_name_plural': 'Dictámenes'},
                ),
                migrations.AlterModelOptions(
                    name='rr',
                    options={'ordering': ['-RR_FEC'], 'verbose_name': 'Recurso de Reconsideración (RR)', 'verbose_name_plural': 'Recursos de Reconsideración (RR)'},
                ),
                migrations.AlterField(
                    model_name='abog_sim',
                    name='abog',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tpe_app.abog', verbose_name='Abogado'),
                ),
                migrations.AlterField(
                    model_name='abog_sim',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='autotpe',
                    name='abog',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
                ),
                migrations.AlterField(
                    model_name='autotpe',
                    name='agenda',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda'),
                ),
                migrations.AlterField(
                    model_name='autotpe',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='autotsp',
                    name='sim',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='dictamen',
                    name='abog',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
                ),
                migrations.AlterField(
                    model_name='dictamen',
                    name='agenda',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.agenda', verbose_name='Agenda'),
                ),
                migrations.AlterField(
                    model_name='dictamen',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='documentoadjunto',
                    name='DOC_TABLA',
                    field=models.CharField(choices=[('sim', 'Sumario SIM'), ('res', 'Resolución TPE'), ('rr', 'Recurso de Reconsideración RR'), ('rap', 'Recurso de Apelación RAP'), ('raee', 'RAEE'), ('autotpe', 'Auto TPE'), ('autotsp', 'Auto TSP')], max_length=30, verbose_name='Tabla de origen'),
                ),
                migrations.AlterField(
                    model_name='pm_sim',
                    name='pm',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tpe_app.pm', verbose_name='Militar'),
                ),
                migrations.AlterField(
                    model_name='pm_sim',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='raee',
                    name='rap',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.rap', verbose_name='Recurso de Apelación'),
                ),
                migrations.AlterField(
                    model_name='raee',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='rap',
                    name='rr',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.rr', verbose_name='Recurso de Reconsideración (RR)'),
                ),
                migrations.AlterField(
                    model_name='rap',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='res',
                    name='abog',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
                ),
                migrations.AlterField(
                    model_name='res',
                    name='agenda',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda'),
                ),
                migrations.AlterField(
                    model_name='res',
                    name='dictamen',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.dictamen', verbose_name='Dictamen origen'),
                ),
                migrations.AlterField(
                    model_name='res',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
                migrations.AlterField(
                    model_name='rr',
                    name='abog',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Abogado'),
                ),
                migrations.AlterField(
                    model_name='rr',
                    name='agenda',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.agenda', verbose_name='Agenda'),
                ),
                migrations.AlterField(
                    model_name='rr',
                    name='res',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.res', verbose_name='Primera Resolución'),
                ),
                migrations.AlterField(
                    model_name='rr',
                    name='sim',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpe_app.sim', verbose_name='Sumario'),
                ),
            ]
        ),
    ]
