# Generated by Django 4.2 on 2026-04-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0038_alter_dictamen_options_alter_rr_options_and_more'),
    ]

    operations = [
    ]
