# Generated by Django 4.2 on 2026-04-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0039_auto_20260407_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictamen',
            options={'ordering': ['-id'], 'verbose_name': 'Dictamen', 'verbose_name_plural': 'Dictámenes'},
        ),
        migrations.AlterModelOptions(
            name='rr',
            options={'ordering': ['-RR_FEC'], 'verbose_name': 'Segunda Resolución (RR)', 'verbose_name_plural': 'Segundas Resoluciones (RR)'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='abog',
                    old_name='id',
                    new_name='abog_id',
                ),
                migrations.RenameField(
                    model_name='pm',
                    old_name='id',
                    new_name='pm_id',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='DOC_TABLA',
            field=models.CharField(choices=[('sim', 'Sumario SIM'), ('res', 'Resolución TPE'), ('rr', 'Segunda Resolución RR'), ('rap', 'Recurso de Apelación RAP'), ('raee', 'RAEE'), ('autotpe', 'Auto TPE'), ('autotsp', 'Auto TSP')], max_length=30, verbose_name='Tabla de origen'),
        ),
        migrations.AlterField(
            model_name='rap',
            name='rr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.rr', verbose_name='Segunda Resolución (RR)'),
        ),
    ]
