# Generated by Django 5.2.12 on 2026-04-08 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0040_alter_dictamen_options_alter_rr_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='abog',
                    name='abog_id',
                    field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='pm',
                    name='pm_id',
                    field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ABOGADO', 'Abogado'), ('BUSCADOR', 'Buscador'), ('AUXILIAR', 'Auxiliar')], max_length=20, verbose_name='Rol/Perfil')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('abogado', models.ForeignKey(blank=True, help_text='Solo para usuarios con rol ABOGADO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpe_app.abog', verbose_name='Vinculado a Abogado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'perfil_usuario',
            },
        ),
    ]
