# Generated by Django 5.2.12 on 2026-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpe_app', '0041_alter_abog_abog_id_alter_pm_pm_id_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm',
            name='PM_FOTO',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pm/', verbose_name='Foto'),
        ),
    ]
